apply plugin: 'com.android.application'

android {
    compileSdk = 36
    namespace 'org.korri.signer.test'

    defaultConfig {
        applicationId 'org.korri.signer.test'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        encoding 'UTF-8'
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }
}

dependencies {
    implementation 'org.bouncycastle:bcprov-jdk18on:1.81'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'androidx.test:core:1.7.0'
    testImplementation 'org.robolectric:robolectric:4.16'
}
