export type PicoDesignPartLayer =
  | "page"
  | "template"
  | "organism"
  | "molecule"
  | "atom"

export interface PicoDesignPart {
  readonly id: string
  readonly layer: PicoDesignPartLayer
  readonly name: string
}

/**
 * Every pico design part, one source of truth. The reusable kit (atom to
 * template) carries data-korri tags on its component root for lab pick-mode;
 * gallery pages are identified by story/pagePartId (only the routed device
 * pages get a distinct page tag), mirroring the Shift precedent.
 */
export const PICO_DESIGN_PARTS = {
  // --- pages (routed, device-mounted) ---
  home: { id: "pico.home", layer: "page", name: "Home" },
  gameDetail: { id: "pico.game-detail", layer: "page", name: "Game Detail" },
  // --- chrome ---
  statusBar: { id: "pico.status-bar", layer: "molecule", name: "Status Bar" },
  // --- templates ---
  gameOverlay: {
    id: "pico.game-overlay",
    layer: "template",
    name: "Game Overlay",
  },
  panelScreen: {
    id: "pico.panel-screen",
    layer: "template",
    name: "Panel Screen",
  },
  screenShell: {
    id: "pico.screen-shell",
    layer: "template",
    name: "Screen Shell",
  },
  // --- organisms ---
  achievementList: {
    id: "pico.achievement-list",
    layer: "organism",
    name: "Achievement List",
  },
  appChoiceList: {
    id: "pico.app-choice-list",
    layer: "organism",
    name: "App Choice List",
  },
  attractLoop: {
    id: "pico.attract-loop",
    layer: "organism",
    name: "Attract Loop",
  },
  bootStepper: {
    id: "pico.boot-stepper",
    layer: "organism",
    name: "Boot Stepper",
  },
  collectionList: {
    id: "pico.collection-list",
    layer: "organism",
    name: "Collection List",
  },
  communityStatPanel: {
    id: "pico.community-stat-panel",
    layer: "organism",
    name: "Community Stat Panel",
  },
  companionCard: {
    id: "pico.companion-card",
    layer: "organism",
    name: "Companion Card",
  },
  continueList: {
    id: "pico.continue-list",
    layer: "organism",
    name: "Continue List",
  },
  controlCenter: {
    id: "pico.control-center",
    layer: "organism",
    name: "Control Center",
  },
  countdownStage: {
    id: "pico.countdown-stage",
    layer: "organism",
    name: "Countdown Stage",
  },
  coverflowRail: {
    id: "pico.coverflow-rail",
    layer: "organism",
    name: "Coverflow Rail",
  },
  crewLobby: { id: "pico.crew-lobby", layer: "organism", name: "Crew Lobby" },
  downloadConfirmCard: {
    id: "pico.download-confirm-card",
    layer: "organism",
    name: "Download Confirm Card",
  },
  downloadProgress: {
    id: "pico.download-progress",
    layer: "organism",
    name: "Download Progress",
  },
  dualPrimaryStage: {
    id: "pico.dual-primary-stage",
    layer: "organism",
    name: "Dual Primary Stage",
  },
  failureList: {
    id: "pico.failure-list",
    layer: "organism",
    name: "Failure List",
  },
  featuredToday: {
    id: "pico.featured-today",
    layer: "organism",
    name: "Featured Today",
  },
  filterSortPanel: {
    id: "pico.filter-sort-panel",
    layer: "organism",
    name: "Filter Sort Panel",
  },
  filtersPanel: {
    id: "pico.filters-panel",
    layer: "organism",
    name: "Filters Panel",
  },
  friendsList: {
    id: "pico.friends-list",
    layer: "organism",
    name: "Friends List",
  },
  friendsPanel: {
    id: "pico.friends-panel",
    layer: "organism",
    name: "Friends Panel",
  },
  hero: { id: "pico.hero", layer: "organism", name: "Hero" },
  hostCardList: {
    id: "pico.host-card-list",
    layer: "organism",
    name: "Host Card List",
  },
  hostScanList: {
    id: "pico.host-scan-list",
    layer: "organism",
    name: "Host Scan List",
  },
  hudOverlay: {
    id: "pico.hud-overlay",
    layer: "organism",
    name: "Hud Overlay",
  },
  inlineSeatStrip: {
    id: "pico.inline-seat-strip",
    layer: "organism",
    name: "Inline Seat Strip",
  },
  installProgress: {
    id: "pico.install-progress",
    layer: "organism",
    name: "Install Progress",
  },
  inviteList: {
    id: "pico.invite-list",
    layer: "organism",
    name: "Invite List",
  },
  joiningStage: {
    id: "pico.joining-stage",
    layer: "organism",
    name: "Joining Stage",
  },
  lastPlayedHero: {
    id: "pico.last-played-hero",
    layer: "organism",
    name: "Last Played Hero",
  },
  launchingStage: {
    id: "pico.launching-stage",
    layer: "organism",
    name: "Launching Stage",
  },
  launchTube: {
    id: "pico.launch-tube",
    layer: "organism",
    name: "Launch Tube",
  },
  leaderboardTable: {
    id: "pico.leaderboard-table",
    layer: "organism",
    name: "Leaderboard Table",
  },
  libraryRail: {
    id: "pico.library-rail",
    layer: "organism",
    name: "Library Rail",
  },
  lobbyArtStage: {
    id: "pico.lobby-art-stage",
    layer: "organism",
    name: "Lobby Art Stage",
  },
  miniHome: { id: "pico.mini-home", layer: "organism", name: "Mini Home" },
  modal: { id: "pico.modal", layer: "organism", name: "Modal" },
  momentHero: {
    id: "pico.moment-hero",
    layer: "organism",
    name: "Moment Hero",
  },
  onScreenKeyboard: {
    id: "pico.on-screen-keyboard",
    layer: "organism",
    name: "On Screen Keyboard",
  },
  playersHub: {
    id: "pico.players-hub",
    layer: "organism",
    name: "Players Hub",
  },
  playerStyleMatrix: {
    id: "pico.player-style-matrix",
    layer: "organism",
    name: "Player Style Matrix",
  },
  playerToast: {
    id: "pico.player-toast",
    layer: "organism",
    name: "Player Toast",
  },
  profileCard: {
    id: "pico.profile-card",
    layer: "organism",
    name: "Profile Card",
  },
  quickLook: { id: "pico.quick-look", layer: "organism", name: "Quick Look" },
  reactiveStage: {
    id: "pico.reactive-stage",
    layer: "organism",
    name: "Reactive Stage",
  },
  releaseList: {
    id: "pico.release-list",
    layer: "organism",
    name: "Release List",
  },
  remapList: { id: "pico.remap-list", layer: "organism", name: "Remap List" },
  repairProgress: {
    id: "pico.repair-progress",
    layer: "organism",
    name: "Repair Progress",
  },
  runningGame: {
    id: "pico.running-game",
    layer: "organism",
    name: "Running Game",
  },
  saveSlotGrid: {
    id: "pico.save-slot-grid",
    layer: "organism",
    name: "Save Slot Grid",
  },
  screenshotGallery: {
    id: "pico.screenshot-gallery",
    layer: "organism",
    name: "Screenshot Gallery",
  },
  searchResults: {
    id: "pico.search-results",
    layer: "organism",
    name: "Search Results",
  },
  seatAssignList: {
    id: "pico.seat-assign-list",
    layer: "organism",
    name: "Seat Assign List",
  },
  seatList: { id: "pico.seat-list", layer: "organism", name: "Seat List" },
  sessionDock: {
    id: "pico.session-dock",
    layer: "organism",
    name: "Session Dock",
  },
  sessionPlayersHud: {
    id: "pico.session-players-hud",
    layer: "organism",
    name: "Session Players Hud",
  },
  shelfGrid: { id: "pico.shelf-grid", layer: "organism", name: "Shelf Grid" },
  spotlightHero: {
    id: "pico.spotlight-hero",
    layer: "organism",
    name: "Spotlight Hero",
  },
  storeView: { id: "pico.store-view", layer: "organism", name: "Store View" },
  streamPanel: {
    id: "pico.stream-panel",
    layer: "organism",
    name: "Stream Panel",
  },
  systemGrid: {
    id: "pico.system-grid",
    layer: "organism",
    name: "System Grid",
  },
  updatePanel: {
    id: "pico.update-panel",
    layer: "organism",
    name: "Update Panel",
  },
  // --- molecules ---
  card: { id: "pico.card", layer: "molecule", name: "Card" },
  detailHead: {
    id: "pico.detail-head",
    layer: "molecule",
    name: "Detail Head",
  },
  gameCart: { id: "pico.game-cart", layer: "molecule", name: "Game Cart" },
  gameCartUnmarked: {
    id: "pico.game-cart-unmarked",
    layer: "molecule",
    name: "Game Cart Unmarked",
  },
  gameLogo: { id: "pico.game-logo", layer: "molecule", name: "Game Logo" },
  hostBadge: { id: "pico.host-badge", layer: "molecule", name: "Host Badge" },
  keyArtBackdrop: {
    id: "pico.key-art-backdrop",
    layer: "molecule",
    name: "Key Art Backdrop",
  },
  list: { id: "pico.list", layer: "molecule", name: "List" },
  opt: { id: "pico.opt", layer: "molecule", name: "Opt" },
  playCta: { id: "pico.play-cta", layer: "molecule", name: "Play Cta" },
  player: { id: "pico.player", layer: "molecule", name: "Player" },
  qualityBar: {
    id: "pico.quality-bar",
    layer: "molecule",
    name: "Quality Bar",
  },
  row: { id: "pico.row", layer: "molecule", name: "Row" },
  searchQuery: {
    id: "pico.search-query",
    layer: "molecule",
    name: "Search Query",
  },
  settingRow: {
    id: "pico.setting-row",
    layer: "molecule",
    name: "Setting Row",
  },
  tabs: { id: "pico.tabs", layer: "molecule", name: "Tabs" },
  // --- atoms ---
  badge: { id: "pico.badge", layer: "atom", name: "Badge" },
  blockBar: { id: "pico.block-bar", layer: "atom", name: "Block Bar" },
  btn: { id: "pico.btn", layer: "atom", name: "Btn" },
  chip: { id: "pico.chip", layer: "atom", name: "Chip" },
  dim: { id: "pico.dim", layer: "atom", name: "Dim" },
  glyph: { id: "pico.glyph", layer: "atom", name: "Glyph" },
  icon: { id: "pico.icon", layer: "atom", name: "Icon" },
  progress: { id: "pico.progress", layer: "atom", name: "Progress" },
  spinner: { id: "pico.spinner", layer: "atom", name: "Spinner" },
  stat: { id: "pico.stat", layer: "atom", name: "Stat" },
  sub: { id: "pico.sub", layer: "atom", name: "Sub" },
  title: { id: "pico.title", layer: "atom", name: "Title" },
  toggle: { id: "pico.toggle", layer: "atom", name: "Toggle" },
  // --- screen leaves ---
  pcAcqUrl: { id: "pico.pcAcq-url", layer: "molecule", name: "Url" },
  pcDataCart: { id: "pico.pcData-cart", layer: "atom", name: "Cart" },
  pcDataGrid: { id: "pico.pcData-grid", layer: "organism", name: "Grid" },
  pcDataState: { id: "pico.pcData-state", layer: "atom", name: "State" },
  pcDataNote: { id: "pico.pcData-note", layer: "molecule", name: "Note" },
  pcDataSwap: { id: "pico.pcData-swap", layer: "atom", name: "Swap" },
  pcDataTag: { id: "pico.pcData-tag", layer: "molecule", name: "Tag" },
  pcDataBar: { id: "pico.pcData-bar", layer: "molecule", name: "Bar" },
  pcData: { id: "pico.pcData", layer: "atom", name: "Data" },
  pcDetChips: { id: "pico.pcDet-chips", layer: "molecule", name: "Chips" },
  pcDetNote: { id: "pico.pcDet-note", layer: "molecule", name: "Note" },
  pcDetActions: {
    id: "pico.pcDet-actions",
    layer: "molecule",
    name: "Actions",
  },
  pcFutTarget: { id: "pico.pcFut-target", layer: "atom", name: "Target" },
  pcFutFeedLine: {
    id: "pico.pcFut-feed-line",
    layer: "molecule",
    name: "Feed Line",
  },
  pcFutFeedText: {
    id: "pico.pcFut-feed-text",
    layer: "atom",
    name: "Feed Text",
  },
  pcFutAva: { id: "pico.pcFut-ava", layer: "molecule", name: "Ava" },
  pcFutFeedRow: {
    id: "pico.pcFut-feed-row",
    layer: "molecule",
    name: "Feed Row",
  },
  pcFutFeed: { id: "pico.pcFut-feed", layer: "organism", name: "Feed" },
  pcFutConfLine: {
    id: "pico.pcFut-conf-line",
    layer: "molecule",
    name: "Conf Line",
  },
  pcFutConfGrid: {
    id: "pico.pcFut-conf-grid",
    layer: "organism",
    name: "Conf Grid",
  },
  pcFutConfNote: {
    id: "pico.pcFut-conf-note",
    layer: "molecule",
    name: "Conf Note",
  },
  pcFutConfHead: {
    id: "pico.pcFut-conf-head",
    layer: "molecule",
    name: "Conf Head",
  },
  pcIgAttempt: { id: "pico.pcIg-attempt", layer: "molecule", name: "Attempt" },
  pcIgReconnect: {
    id: "pico.pcIg-reconnect",
    layer: "molecule",
    name: "Reconnect",
  },
  pcLibCaption: {
    id: "pico.pcLib-caption",
    layer: "molecule",
    name: "Caption",
  },
  pcMCta: { id: "pico.pcM-cta", layer: "molecule", name: "Cta" },
  pcMActions: { id: "pico.pcM-actions", layer: "molecule", name: "Actions" },
  pcMMeta: { id: "pico.pcM-meta", layer: "molecule", name: "Meta" },
  pcMProgressFill: {
    id: "pico.pcM-progress-fill",
    layer: "atom",
    name: "Progress Fill",
  },
  pcMProgress: { id: "pico.pcM-progress", layer: "atom", name: "Progress" },
  pcMNew: { id: "pico.pcM-new", layer: "molecule", name: "New" },
  pcMPres: { id: "pico.pcM-pres", layer: "molecule", name: "Pres" },
  pcMFriendText: {
    id: "pico.pcM-friend-text",
    layer: "atom",
    name: "Friend Text",
  },
  pcMFriend: { id: "pico.pcM-friend", layer: "molecule", name: "Friend" },
  pcMoodLabel: { id: "pico.pcMood-label", layer: "molecule", name: "Label" },
  pcMoodArt: { id: "pico.pcMood-art", layer: "atom", name: "Art" },
  pcMoodTile: { id: "pico.pcMood-tile", layer: "molecule", name: "Tile" },
  pcMoodTiles: { id: "pico.pcMood-tiles", layer: "atom", name: "Tiles" },
  pcMoodKicker: { id: "pico.pcMood-kicker", layer: "molecule", name: "Kicker" },
  pcMood: { id: "pico.pcMood", layer: "atom", name: "Mood" },
  pcMTag: { id: "pico.pcM-tag", layer: "molecule", name: "Tag" },
  pcMTags: { id: "pico.pcM-tags", layer: "atom", name: "Tags" },
  pcMSlot: { id: "pico.pcM-slot", layer: "atom", name: "Slot" },
  pcMSave: { id: "pico.pcM-save", layer: "atom", name: "Save" },
  pcMNext: { id: "pico.pcM-next", layer: "atom", name: "Next" },
  pcMRarity: { id: "pico.pcM-rarity", layer: "atom", name: "Rarity" },
  pcMBadge: { id: "pico.pcM-badge", layer: "molecule", name: "Badge" },
  pcMGreet: { id: "pico.pcM-greet", layer: "atom", name: "Greet" },
  pcMdStep: { id: "pico.pcMd-step", layer: "molecule", name: "Step" },
  pcMdSteps: { id: "pico.pcMd-steps", layer: "atom", name: "Steps" },
  pcMdConnect: { id: "pico.pcMd-connect", layer: "atom", name: "Connect" },
  pcHeroMsg: { id: "pico.pc-hero-msg", layer: "molecule", name: "Hero Msg" },
  pcMdPairWait: { id: "pico.pcMd-pair-wait", layer: "atom", name: "Pair Wait" },
  pcMdCode: { id: "pico.pcMd-code", layer: "atom", name: "Code" },
  pcMdPair: { id: "pico.pcMd-pair", layer: "atom", name: "Pair" },
  pcMpCode: { id: "pico.pcMp-code", layer: "atom", name: "Code" },
  pcMpJoinSide: { id: "pico.pcMp-join-side", layer: "atom", name: "Join Side" },
  pcMpQrRow: { id: "pico.pcMp-qr-row", layer: "molecule", name: "Qr Row" },
  pcMpQr: { id: "pico.pcMp-qr", layer: "atom", name: "Qr" },
  pcMpJoin: { id: "pico.pcMp-join", layer: "atom", name: "Join" },
  pcMpFailedActions: {
    id: "pico.pcMp-failed-actions",
    layer: "molecule",
    name: "Failed Actions",
  },
  pcMpFailed: { id: "pico.pcMp-failed", layer: "atom", name: "Failed" },
  pcMpDevName: {
    id: "pico.pcMp-dev-name",
    layer: "molecule",
    name: "Dev Name",
  },
  pcMpNearby: { id: "pico.pcMp-nearby", layer: "atom", name: "Nearby" },
  pcMpNearbyHead: {
    id: "pico.pcMp-nearby-head",
    layer: "molecule",
    name: "Nearby Head",
  },
  pcPerPostCaret: {
    id: "pico.pcPer-post-caret",
    layer: "atom",
    name: "Post Caret",
  },
  pcPerPostLine: {
    id: "pico.pcPer-post-line",
    layer: "molecule",
    name: "Post Line",
  },
  pcPerPostLines: {
    id: "pico.pcPer-post-lines",
    layer: "atom",
    name: "Post Lines",
  },
  pcPerPost: { id: "pico.pcPer-post", layer: "atom", name: "Post" },
  pcPerMoodLabel: {
    id: "pico.pcPer-mood-label",
    layer: "molecule",
    name: "Mood Label",
  },
  pcPerMood: { id: "pico.pcPer-mood", layer: "molecule", name: "Mood" },
  pcPerMoods: { id: "pico.pcPer-moods", layer: "atom", name: "Moods" },
  pcSesReason: { id: "pico.pcSes-reason", layer: "atom", name: "Reason" },
  pcSesReasons: { id: "pico.pcSes-reasons", layer: "atom", name: "Reasons" },
  pcSesCountdown: {
    id: "pico.pcSes-countdown",
    layer: "atom",
    name: "Countdown",
  },
  pcSesStageV: { id: "pico.pcSes-stage-v", layer: "atom", name: "Stage V" },
  pcSesStageK: { id: "pico.pcSes-stage-k", layer: "atom", name: "Stage K" },
  pcSesStage: { id: "pico.pcSes-stage", layer: "organism", name: "Stage" },
  pcSesFailBannerText: {
    id: "pico.pcSes-fail-banner-text",
    layer: "atom",
    name: "Fail Banner Text",
  },
  pcSesFailBannerIco: {
    id: "pico.pcSes-fail-banner-ico",
    layer: "atom",
    name: "Fail Banner Ico",
  },
  pcSesFailBanner: {
    id: "pico.pcSes-fail-banner",
    layer: "molecule",
    name: "Fail Banner",
  },
  pcSetActions: {
    id: "pico.pcSet-actions",
    layer: "molecule",
    name: "Actions",
  },
  pcSetInfo: { id: "pico.pcSet-info", layer: "molecule", name: "Info" },
  pcSetProfileMeta: {
    id: "pico.pcSet-profile-meta",
    layer: "molecule",
    name: "Profile Meta",
  },
  pcSetLabel: { id: "pico.pcSet-label", layer: "molecule", name: "Label" },
  pcSetProfileText: {
    id: "pico.pcSet-profile-text",
    layer: "atom",
    name: "Profile Text",
  },
  pcSetAvatar: { id: "pico.pcSet-avatar", layer: "molecule", name: "Avatar" },
  pcSetProfile: {
    id: "pico.pcSet-profile",
    layer: "molecule",
    name: "Profile",
  },
  pcSetList: { id: "pico.pcSet-list", layer: "organism", name: "List" },
  pcSetModalDesc: {
    id: "pico.pcSet-modal-desc",
    layer: "atom",
    name: "Modal Desc",
  },
  pcSetSwatch: { id: "pico.pcSet-swatch", layer: "molecule", name: "Swatch" },
  pcSetRow: { id: "pico.pcSet-row", layer: "molecule", name: "Row" },
  pcSetFree: { id: "pico.pcSet-free", layer: "atom", name: "Free" },
  pcSetUsed: { id: "pico.pcSet-used", layer: "atom", name: "Used" },
  pcSetUsage: { id: "pico.pcSet-usage", layer: "atom", name: "Usage" },
  pcSetAccent: { id: "pico.pcSet-accent", layer: "molecule", name: "Accent" },
  pcSetAccents: { id: "pico.pcSet-accents", layer: "atom", name: "Accents" },
  pcSetThemeName: {
    id: "pico.pcSet-theme-name",
    layer: "molecule",
    name: "Theme Name",
  },
  pcSetThemeSwatch: {
    id: "pico.pcSet-theme-swatch",
    layer: "molecule",
    name: "Theme Swatch",
  },
  pcSetTheme: { id: "pico.pcSet-theme", layer: "molecule", name: "Theme" },
  pcSetThemeTick: {
    id: "pico.pcSet-theme-tick",
    layer: "atom",
    name: "Theme Tick",
  },
  pcSetThemes: { id: "pico.pcSet-themes", layer: "atom", name: "Themes" },
  pcLast: { id: "pico.pcLast", layer: "atom", name: "Last" },
  pcLastEmpty: { id: "pico.pcLast-empty", layer: "atom", name: "Empty" },
  pcShowSpot: { id: "pico.pcShow-spot", layer: "atom", name: "Spot" },
  pcSysBootVer: { id: "pico.pcSys-boot-ver", layer: "atom", name: "Boot Ver" },
  pcSysBootSub: { id: "pico.pcSys-boot-sub", layer: "atom", name: "Boot Sub" },
  pcSysLogo: { id: "pico.pcSys-logo", layer: "atom", name: "Logo" },
  pcSysBoot: { id: "pico.pcSys-boot", layer: "atom", name: "Boot" },
  pcSysDevbadge: { id: "pico.pcSys-devbadge", layer: "atom", name: "Devbadge" },
  pcSysStub: { id: "pico.pcSys-stub", layer: "molecule", name: "Stub" },
  pcSysToastText: {
    id: "pico.pcSys-toast-text",
    layer: "atom",
    name: "Toast Text",
  },
  pcSysToastIco: {
    id: "pico.pcSys-toast-ico",
    layer: "atom",
    name: "Toast Ico",
  },
  pcSysToast: { id: "pico.pcSys-toast", layer: "molecule", name: "Toast" },
  pcSysStep: { id: "pico.pcSys-step", layer: "molecule", name: "Step" },
  pcSysSteps: { id: "pico.pcSys-steps", layer: "atom", name: "Steps" },
  pcSysCode: { id: "pico.pcSys-code", layer: "atom", name: "Code" },
  pcSysPower: { id: "pico.pcSys-power", layer: "atom", name: "Power" },
  pcSysUpdBar: { id: "pico.pcSys-upd-bar", layer: "molecule", name: "Upd Bar" },
  pcFutRarity: { id: "pico.pcFut-rarity", layer: "atom", name: "Rarity" },
  pcFutAchIco: { id: "pico.pcFut-ach-ico", layer: "atom", name: "Ach Ico" },
  pcFutAchToastText: {
    id: "pico.pcFut-ach-toast-text",
    layer: "atom",
    name: "Ach Toast Text",
  },
  pcFutAchToastIco: {
    id: "pico.pcFut-ach-toast-ico",
    layer: "atom",
    name: "Ach Toast Ico",
  },
  pcFutAchToast: {
    id: "pico.pcFut-ach-toast",
    layer: "molecule",
    name: "Ach Toast",
  },
  pcDetChoiceMeta: {
    id: "pico.pcDet-choice-meta",
    layer: "molecule",
    name: "Choice Meta",
  },
  pcPerPress: { id: "pico.pcPer-press", layer: "atom", name: "Press" },
  pcPerHiscore: { id: "pico.pcPer-hiscore", layer: "atom", name: "Hiscore" },
  pcPerAttractCart: {
    id: "pico.pcPer-attract-cart",
    layer: "atom",
    name: "Attract Cart",
  },
  pcPerAttractRail: {
    id: "pico.pcPer-attract-rail",
    layer: "organism",
    name: "Attract Rail",
  },
  pcPerLogo: { id: "pico.pcPer-logo", layer: "atom", name: "Logo" },
  pcPerAttractMid: {
    id: "pico.pcPer-attract-mid",
    layer: "atom",
    name: "Attract Mid",
  },
  pcPerStars: { id: "pico.pcPer-stars", layer: "atom", name: "Stars" },
  pcSesBootBar: {
    id: "pico.pcSes-boot-bar",
    layer: "molecule",
    name: "Boot Bar",
  },
  pcSesStepLabel: {
    id: "pico.pcSes-step-label",
    layer: "molecule",
    name: "Step Label",
  },
  pcSesStepMark: {
    id: "pico.pcSes-step-mark",
    layer: "atom",
    name: "Step Mark",
  },
  pcSesStep: { id: "pico.pcSes-step", layer: "molecule", name: "Step" },
  pcSesSteps: { id: "pico.pcSes-steps", layer: "atom", name: "Steps" },
  pcDetDiffRow: {
    id: "pico.pcDet-diff-row",
    layer: "molecule",
    name: "Diff Row",
  },
  pcMdCompanionDev: {
    id: "pico.pcMd-companion-dev",
    layer: "atom",
    name: "Companion Dev",
  },
  pcMdCompanionOverlay: {
    id: "pico.pcMd-companion-overlay",
    layer: "atom",
    name: "Companion Overlay",
  },
  pcArt: { id: "pico.pc-art", layer: "atom", name: "Art" },
  pcMdCompanionArt: {
    id: "pico.pcMd-companion-art",
    layer: "atom",
    name: "Companion Art",
  },
  pcCCTile: { id: "pico.pcCC-tile", layer: "molecule", name: "Tile" },
  pcCCTiles: { id: "pico.pcCC-tiles", layer: "atom", name: "Tiles" },
  pcCCRow: { id: "pico.pcCC-row", layer: "molecule", name: "Row" },
  pcCCWho: { id: "pico.pcCC-who", layer: "atom", name: "Who" },
  pcCCProfile: { id: "pico.pcCC-profile", layer: "molecule", name: "Profile" },
  pcMpRow: { id: "pico.pcMp-row", layer: "molecule", name: "Row" },
  pcMpCountNum: { id: "pico.pcMp-count-num", layer: "atom", name: "Count Num" },
  pcShowRailCart: {
    id: "pico.pcShow-rail-cart",
    layer: "atom",
    name: "Rail Cart",
  },
  pcMpCrewFoot: {
    id: "pico.pcMp-crew-foot",
    layer: "molecule",
    name: "Crew Foot",
  },
  pcMpCrewSlot: { id: "pico.pcMp-crew-slot", layer: "atom", name: "Crew Slot" },
  pcMpCrewSlots: {
    id: "pico.pcMp-crew-slots",
    layer: "organism",
    name: "Crew Slots",
  },
  pcMpCrewMarquee: {
    id: "pico.pcMp-crew-marquee",
    layer: "atom",
    name: "Crew Marquee",
  },
  pcHeroActions: {
    id: "pico.pc-hero-actions",
    layer: "molecule",
    name: "Hero Actions",
  },
  pcAcqMeta: { id: "pico.pcAcq-meta", layer: "molecule", name: "Meta" },
  pcAcqConfirmBody: {
    id: "pico.pcAcq-confirm-body",
    layer: "organism",
    name: "Confirm Body",
  },
  pcAcqStats: { id: "pico.pcAcq-stats", layer: "atom", name: "Stats" },
  pcMdLaunchRow: {
    id: "pico.pcMd-launch-row",
    layer: "molecule",
    name: "Launch Row",
  },
  pcMdPrimaryInfo: {
    id: "pico.pcMd-primary-info",
    layer: "molecule",
    name: "Primary Info",
  },
  pcMdRail: { id: "pico.pcMd-rail", layer: "organism", name: "Rail" },
  pcMdPrimary: { id: "pico.pcMd-primary", layer: "atom", name: "Primary" },
  pcMdDot: { id: "pico.pcMd-dot", layer: "atom", name: "Dot" },
  pcSesFailDetail: {
    id: "pico.pcSes-fail-detail",
    layer: "atom",
    name: "Fail Detail",
  },
  pcSesFailTitle: {
    id: "pico.pcSes-fail-title",
    layer: "atom",
    name: "Fail Title",
  },
  pcSesFail: { id: "pico.pcSes-fail", layer: "atom", name: "Fail" },
  pcFutFeatRail: {
    id: "pico.pcFut-feat-rail",
    layer: "organism",
    name: "Feat Rail",
  },
  pcFutGroupH: { id: "pico.pcFut-group-h", layer: "atom", name: "Group H" },
  pcFutFeatMore: {
    id: "pico.pcFut-feat-more",
    layer: "atom",
    name: "Feat More",
  },
  pcFutFeatActions: {
    id: "pico.pcFut-feat-actions",
    layer: "molecule",
    name: "Feat Actions",
  },
  pcFutFeatWhy: { id: "pico.pcFut-feat-why", layer: "atom", name: "Feat Why" },
  pcFutFeatBlurb: {
    id: "pico.pcFut-feat-blurb",
    layer: "atom",
    name: "Feat Blurb",
  },
  pcFutFeatTags: {
    id: "pico.pcFut-feat-tags",
    layer: "atom",
    name: "Feat Tags",
  },
  pcFutFeatInfo: {
    id: "pico.pcFut-feat-info",
    layer: "molecule",
    name: "Feat Info",
  },
  pcFutFeatTop: {
    id: "pico.pcFut-feat-top",
    layer: "molecule",
    name: "Feat Top",
  },
  pcCardTitle: { id: "pico.pc-card-title", layer: "atom", name: "Card Title" },
  pcLibSection: {
    id: "pico.pcLib-section",
    layer: "organism",
    name: "Section",
  },
  pcLibSortRest: {
    id: "pico.pcLib-sort-rest",
    layer: "atom",
    name: "Sort Rest",
  },
  pcFilSection: {
    id: "pico.pcFil-section",
    layer: "organism",
    name: "Section",
  },
  pcFilChips: { id: "pico.pcFil-chips", layer: "molecule", name: "Chips" },
  pcFilItem: { id: "pico.pcFil-item", layer: "molecule", name: "Item" },
  pcFilList: { id: "pico.pcFil-list", layer: "organism", name: "List" },
  pcFutDot: { id: "pico.pcFut-dot", layer: "atom", name: "Dot" },
  pcFutGroup: { id: "pico.pcFut-group", layer: "molecule", name: "Group" },
  pcFrCta: { id: "pico.pcFr-cta", layer: "molecule", name: "Cta" },
  pcFrText: { id: "pico.pcFr-text", layer: "atom", name: "Text" },
  pcMpPres: { id: "pico.pcMp-pres", layer: "molecule", name: "Pres" },
  pcFrRow: { id: "pico.pcFr-row", layer: "molecule", name: "Row" },
  pcMdHostCta: {
    id: "pico.pcMd-host-cta",
    layer: "molecule",
    name: "Host Cta",
  },
  pcMdHostAddr: { id: "pico.pcMd-host-addr", layer: "atom", name: "Host Addr" },
  pcMdHostMeta: {
    id: "pico.pcMd-host-meta",
    layer: "molecule",
    name: "Host Meta",
  },
  pcMdHostName: {
    id: "pico.pcMd-host-name",
    layer: "molecule",
    name: "Host Name",
  },
  pcMdHostHead: {
    id: "pico.pcMd-host-head",
    layer: "molecule",
    name: "Host Head",
  },
  pcMdFade: { id: "pico.pcMd-fade", layer: "atom", name: "Fade" },
  pcIgToastIco: { id: "pico.pcIg-toast-ico", layer: "atom", name: "Toast Ico" },
  pcIgToast: { id: "pico.pcIg-toast", layer: "molecule", name: "Toast" },
  pcIgRead: { id: "pico.pcIg-read", layer: "molecule", name: "Read" },
  pcIgHudCorner: {
    id: "pico.pcIg-hud-corner",
    layer: "molecule",
    name: "Hud Corner",
  },
  pcMpStripPlayers: {
    id: "pico.pcMp-strip-players",
    layer: "organism",
    name: "Strip Players",
  },
  pcMpStrip: { id: "pico.pcMp-strip", layer: "atom", name: "Strip" },
  pcMpInlineCart: {
    id: "pico.pcMp-inline-cart",
    layer: "atom",
    name: "Inline Cart",
  },
  pcMpInlineRail: {
    id: "pico.pcMp-inline-rail",
    layer: "organism",
    name: "Inline Rail",
  },
  pcAcqStepLabel: {
    id: "pico.pcAcq-step-label",
    layer: "molecule",
    name: "Step Label",
  },
  pcAcqStepMark: {
    id: "pico.pcAcq-step-mark",
    layer: "atom",
    name: "Step Mark",
  },
  pcAcqStep: { id: "pico.pcAcq-step", layer: "molecule", name: "Step" },
  pcMpInviteCta: {
    id: "pico.pcMp-invite-cta",
    layer: "molecule",
    name: "Invite Cta",
  },
  pcMpInviteName: {
    id: "pico.pcMp-invite-name",
    layer: "molecule",
    name: "Invite Name",
  },
  pcMpInviteRow: {
    id: "pico.pcMp-invite-row",
    layer: "molecule",
    name: "Invite Row",
  },
  pcMpStep: { id: "pico.pcMp-step", layer: "molecule", name: "Step" },
  pcMpSteps: { id: "pico.pcMp-steps", layer: "atom", name: "Steps" },
  pcMpJoiningArt: {
    id: "pico.pcMp-joining-art",
    layer: "atom",
    name: "Joining Art",
  },
  pcLastMeta: { id: "pico.pcLast-meta", layer: "molecule", name: "Meta" },
  pcLastKicker: { id: "pico.pcLast-kicker", layer: "molecule", name: "Kicker" },
  pcLastInner: { id: "pico.pcLast-inner", layer: "atom", name: "Inner" },
  pcPerPowerName: {
    id: "pico.pcPer-power-name",
    layer: "molecule",
    name: "Power Name",
  },
  pcPerPowerTitle: {
    id: "pico.pcPer-power-title",
    layer: "atom",
    name: "Power Title",
  },
  pcPerPowerGame: {
    id: "pico.pcPer-power-game",
    layer: "atom",
    name: "Power Game",
  },
  pcPerPowerLine: {
    id: "pico.pcPer-power-line",
    layer: "molecule",
    name: "Power Line",
  },
  pcPerPower: { id: "pico.pcPer-power", layer: "atom", name: "Power" },
  pcPerCart: { id: "pico.pcPer-cart", layer: "atom", name: "Cart" },
  pcPerSlot: { id: "pico.pcPer-slot", layer: "atom", name: "Slot" },
  pcPerTube: { id: "pico.pcPer-tube", layer: "organism", name: "Tube" },
  pcSesLaunchStatus: {
    id: "pico.pcSes-launch-status",
    layer: "atom",
    name: "Launch Status",
  },
  pcFutLbScore: {
    id: "pico.pcFut-lb-score",
    layer: "molecule",
    name: "Lb Score",
  },
  pcFutLbName: { id: "pico.pcFut-lb-name", layer: "molecule", name: "Lb Name" },
  pcFutLbRank: { id: "pico.pcFut-lb-rank", layer: "molecule", name: "Lb Rank" },
  pcFutLbRow: { id: "pico.pcFut-lb-row", layer: "molecule", name: "Lb Row" },
  pcFutLb: { id: "pico.pcFut-lb", layer: "atom", name: "Lb" },
  pcLibCart: { id: "pico.pcLib-cart", layer: "atom", name: "Cart" },
  pcMpLobbyASeats: {
    id: "pico.pcMp-lobbyA-seats",
    layer: "atom",
    name: "Lobby A Seats",
  },
  pcMpLobbyAHead: {
    id: "pico.pcMp-lobbyA-head",
    layer: "molecule",
    name: "Lobby A Head",
  },
  pcHomeCart: { id: "pico.pcHome-cart", layer: "atom", name: "Cart" },
  pcHomeGrid: { id: "pico.pcHome-grid", layer: "organism", name: "Grid" },
  pcHomeTitle: { id: "pico.pcHome-title", layer: "atom", name: "Title" },
  pcModalTitle: {
    id: "pico.pc-modal-title",
    layer: "atom",
    name: "Modal Title",
  },
  pcModalPanel: {
    id: "pico.pc-modal-panel",
    layer: "organism",
    name: "Modal Panel",
  },
  pcModal: { id: "pico.pc-modal", layer: "molecule", name: "Modal" },
  pcGamebg: { id: "pico.pc-gamebg", layer: "atom", name: "Gamebg" },
  pcMKicker: { id: "pico.pcM-kicker", layer: "molecule", name: "Kicker" },
  pcMInner: { id: "pico.pcM-inner", layer: "atom", name: "Inner" },
  pcM: { id: "pico.pcM", layer: "atom", name: "M" },
  pcLibKey: { id: "pico.pcLib-key", layer: "atom", name: "Key" },
  pcLibKeyrow: { id: "pico.pcLib-keyrow", layer: "atom", name: "Keyrow" },
  pcMpStylesLabel: {
    id: "pico.pcMp-styles-label",
    layer: "molecule",
    name: "Styles Label",
  },
  pcMpStylesRow: {
    id: "pico.pcMp-styles-row",
    layer: "molecule",
    name: "Styles Row",
  },
  pcMpToastText: {
    id: "pico.pcMp-toast-text",
    layer: "atom",
    name: "Toast Text",
  },
  pcMpToast: { id: "pico.pcMp-toast", layer: "molecule", name: "Toast" },
  pcMpFriendName: {
    id: "pico.pcMp-friend-name",
    layer: "molecule",
    name: "Friend Name",
  },
  pcMpFriend: { id: "pico.pcMp-friend", layer: "molecule", name: "Friend" },
  pcMpHubSeat: { id: "pico.pcMp-hub-seat", layer: "atom", name: "Hub Seat" },
  pcMpHubCols: { id: "pico.pcMp-hub-cols", layer: "atom", name: "Hub Cols" },
  pcMpHubSessionInfo: {
    id: "pico.pcMp-hub-session-info",
    layer: "molecule",
    name: "Hub Session Info",
  },
  pcFutProfChips: {
    id: "pico.pcFut-prof-chips",
    layer: "molecule",
    name: "Prof Chips",
  },
  pcFutProfStats: {
    id: "pico.pcFut-prof-stats",
    layer: "atom",
    name: "Prof Stats",
  },
  pcFutProfXp: { id: "pico.pcFut-prof-xp", layer: "atom", name: "Prof Xp" },
  pcFutProfId: { id: "pico.pcFut-prof-id", layer: "atom", name: "Prof Id" },
  pcFutProfAva: {
    id: "pico.pcFut-prof-ava",
    layer: "molecule",
    name: "Prof Ava",
  },
  pcQLStats: { id: "pico.pcQL-stats", layer: "atom", name: "Stats" },
  pcQLMeta: { id: "pico.pcQL-meta", layer: "molecule", name: "Meta" },
  pcQLTitle: { id: "pico.pcQL-title", layer: "atom", name: "Title" },
  pcPerReactCrtMsg: {
    id: "pico.pcPer-react-crt-msg",
    layer: "molecule",
    name: "React Crt Msg",
  },
  pcPerReactCrtLine: {
    id: "pico.pcPer-react-crt-line",
    layer: "molecule",
    name: "React Crt Line",
  },
  pcPerReactCrt: {
    id: "pico.pcPer-react-crt",
    layer: "atom",
    name: "React Crt",
  },
  pcPerReactName: {
    id: "pico.pcPer-react-name",
    layer: "molecule",
    name: "React Name",
  },
  pcPerReactCap: {
    id: "pico.pcPer-react-cap",
    layer: "atom",
    name: "React Cap",
  },
  pcPerReactCart: {
    id: "pico.pcPer-react-cart",
    layer: "atom",
    name: "React Cart",
  },
  pcPerReactRail: {
    id: "pico.pcPer-react-rail",
    layer: "organism",
    name: "React Rail",
  },
  pcPerReactPixl: {
    id: "pico.pcPer-react-pixl",
    layer: "atom",
    name: "React Pixl",
  },
  pcIgRemapBtn: { id: "pico.pcIg-remap-btn", layer: "atom", name: "Remap Btn" },
  pcIgRemapArrow: {
    id: "pico.pcIg-remap-arrow",
    layer: "atom",
    name: "Remap Arrow",
  },
  pcIgRemapAct: { id: "pico.pcIg-remap-act", layer: "atom", name: "Remap Act" },
  pcIgRemapRow: {
    id: "pico.pcIg-remap-row",
    layer: "molecule",
    name: "Remap Row",
  },
  pcAcqFileName: {
    id: "pico.pcAcq-file-name",
    layer: "molecule",
    name: "File Name",
  },
  pcAcqFile: { id: "pico.pcAcq-file", layer: "atom", name: "File" },
  pcNowDot: { id: "pico.pcNow-dot", layer: "atom", name: "Dot" },
  pcNowTag: { id: "pico.pcNow-tag", layer: "molecule", name: "Tag" },
  pcIgSlotRestore: {
    id: "pico.pcIg-slot-restore",
    layer: "atom",
    name: "Slot Restore",
  },
  pcIgSlotStamp: {
    id: "pico.pcIg-slot-stamp",
    layer: "atom",
    name: "Slot Stamp",
  },
  pcIgSlotLabel: {
    id: "pico.pcIg-slot-label",
    layer: "molecule",
    name: "Slot Label",
  },
  pcIgSlotNo: { id: "pico.pcIg-slot-no", layer: "atom", name: "Slot No" },
  pcIgSlot: { id: "pico.pcIg-slot", layer: "atom", name: "Slot" },
  pcDetStrip: { id: "pico.pcDet-strip", layer: "atom", name: "Strip" },
  pcDetShotCap: { id: "pico.pcDet-shot-cap", layer: "atom", name: "Shot Cap" },
  pcDetShotArt: { id: "pico.pcDet-shot-art", layer: "atom", name: "Shot Art" },
  pcDetShot: { id: "pico.pcDet-shot", layer: "atom", name: "Shot" },
  pcMpAssignAct: {
    id: "pico.pcMp-assign-act",
    layer: "atom",
    name: "Assign Act",
  },
  pcMpAssignCtrl: {
    id: "pico.pcMp-assign-ctrl",
    layer: "atom",
    name: "Assign Ctrl",
  },
  pcMpAssignSeat: {
    id: "pico.pcMp-assign-seat",
    layer: "atom",
    name: "Assign Seat",
  },
  pcMdActive: { id: "pico.pcMd-active", layer: "atom", name: "Active" },
  pcMdSeatBatt: {
    id: "pico.pcMd-seat-batt",
    layer: "molecule",
    name: "Seat Batt",
  },
  pcMdSeatKind: { id: "pico.pcMd-seat-kind", layer: "atom", name: "Seat Kind" },
  pcMdSeatMeta: {
    id: "pico.pcMd-seat-meta",
    layer: "molecule",
    name: "Seat Meta",
  },
  pcNowActions: {
    id: "pico.pcNow-actions",
    layer: "molecule",
    name: "Actions",
  },
  pcNowStats: { id: "pico.pcNow-stats", layer: "atom", name: "Stats" },
  pcNowSect: { id: "pico.pcNow-sect", layer: "molecule", name: "Sect" },
  pcNowSave: { id: "pico.pcNow-save", layer: "atom", name: "Save" },
  pcNowSaves: { id: "pico.pcNow-saves", layer: "atom", name: "Saves" },
  pcNowPlayers: {
    id: "pico.pcNow-players",
    layer: "organism",
    name: "Players",
  },
  pcMpSessionFoot: {
    id: "pico.pcMp-session-foot",
    layer: "molecule",
    name: "Session Foot",
  },
  pcMpHudSig: { id: "pico.pcMp-hud-sig", layer: "atom", name: "Hud Sig" },
  pcMpHudLives: { id: "pico.pcMp-hud-lives", layer: "atom", name: "Hud Lives" },
  pcMpHud: { id: "pico.pcMp-hud", layer: "organism", name: "Hud" },
  pcMpSessionGrid: {
    id: "pico.pcMp-session-grid",
    layer: "organism",
    name: "Session Grid",
  },
  pcShowTile: { id: "pico.pcShow-tile", layer: "molecule", name: "Tile" },
  pcShowShelfRow: {
    id: "pico.pcShow-shelf-row",
    layer: "molecule",
    name: "Shelf Row",
  },
  pcShowShelfTitle: {
    id: "pico.pcShow-shelf-title",
    layer: "atom",
    name: "Shelf Title",
  },
  pcShowShelf: { id: "pico.pcShow-shelf", layer: "organism", name: "Shelf" },
  pcShowSpotTags: {
    id: "pico.pcShow-spot-tags",
    layer: "atom",
    name: "Spot Tags",
  },
  pcShowKicker: { id: "pico.pcShow-kicker", layer: "molecule", name: "Kicker" },
  pcShowSpotInfo: {
    id: "pico.pcShow-spot-info",
    layer: "molecule",
    name: "Spot Info",
  },
  pcShowSpotArt: {
    id: "pico.pcShow-spot-art",
    layer: "atom",
    name: "Spot Art",
  },
  pcShowSpotHero: {
    id: "pico.pcShow-spot-hero",
    layer: "molecule",
    name: "Spot Hero",
  },
  pcShowSpotBg: { id: "pico.pcShow-spot-bg", layer: "atom", name: "Spot Bg" },
  pcFutStoreTileMeta: {
    id: "pico.pcFut-store-tile-meta",
    layer: "molecule",
    name: "Store Tile Meta",
  },
  pcFutStoreTileTitle: {
    id: "pico.pcFut-store-tile-title",
    layer: "atom",
    name: "Store Tile Title",
  },
  pcFutStoreTileBody: {
    id: "pico.pcFut-store-tile-body",
    layer: "organism",
    name: "Store Tile Body",
  },
  pcFutStoreTileArt: {
    id: "pico.pcFut-store-tile-art",
    layer: "atom",
    name: "Store Tile Art",
  },
  pcFutStoreGrid: {
    id: "pico.pcFut-store-grid",
    layer: "organism",
    name: "Store Grid",
  },
  pcFutStoreBannerTag: {
    id: "pico.pcFut-store-banner-tag",
    layer: "molecule",
    name: "Store Banner Tag",
  },
  pcFutStoreBannerMeta: {
    id: "pico.pcFut-store-banner-meta",
    layer: "molecule",
    name: "Store Banner Meta",
  },
  pcFutStoreBlurb: {
    id: "pico.pcFut-store-blurb",
    layer: "atom",
    name: "Store Blurb",
  },
  pcFutStoreBannerText: {
    id: "pico.pcFut-store-banner-text",
    layer: "atom",
    name: "Store Banner Text",
  },
  pcIgStreamCtl: {
    id: "pico.pcIg-stream-ctl",
    layer: "atom",
    name: "Stream Ctl",
  },
  pcIgStreamStats: {
    id: "pico.pcIg-stream-stats",
    layer: "atom",
    name: "Stream Stats",
  },
  pcIgStreamName: {
    id: "pico.pcIg-stream-name",
    layer: "molecule",
    name: "Stream Name",
  },
  pcLibSystemName: {
    id: "pico.pcLib-system-name",
    layer: "molecule",
    name: "System Name",
  },
  pcLibSystem: { id: "pico.pcLib-system", layer: "atom", name: "System" },
  pcAcqNotes: { id: "pico.pcAcq-notes", layer: "atom", name: "Notes" },
  pcAcqArrow: { id: "pico.pcAcq-arrow", layer: "atom", name: "Arrow" },
  pcAcqVersions: { id: "pico.pcAcq-versions", layer: "atom", name: "Versions" },
  // --- screen leaves ---
  pcDetTags: { id: "pico.pcDet-tags", layer: "atom", name: "Tags" },
  pcDetHeadInfo: {
    id: "pico.pcDet-head-info",
    layer: "molecule",
    name: "Head Info",
  },
  pcPlayerSub: { id: "pico.pcPlayer-sub", layer: "atom", name: "Sub" },
  pcPlayerName: { id: "pico.pcPlayer-name", layer: "molecule", name: "Name" },
  pcPlayerMark: { id: "pico.pcPlayer-mark", layer: "atom", name: "Mark" },
  pcPlayerTag: { id: "pico.pcPlayer-tag", layer: "molecule", name: "Tag" },
  pcPlayerOpen: { id: "pico.pcPlayer-open", layer: "atom", name: "Open" },
  pcIgQualityTag: {
    id: "pico.pcIg-quality-tag",
    layer: "molecule",
    name: "Quality Tag",
  },
  pcIgQualityBar: {
    id: "pico.pcIg-quality-bar",
    layer: "molecule",
    name: "Quality Bar",
  },
  pcIgQualityLabel: {
    id: "pico.pcIg-quality-label",
    layer: "molecule",
    name: "Quality Label",
  },
  pcRowTrail: { id: "pico.pc-row-trail", layer: "atom", name: "Row Trail" },
  pcRowMeta: { id: "pico.pc-row-meta", layer: "molecule", name: "Row Meta" },
  pcRowLabel: { id: "pico.pc-row-label", layer: "molecule", name: "Row Label" },
  pcRowText: { id: "pico.pc-row-text", layer: "atom", name: "Row Text" },
  pcRowIco: { id: "pico.pc-row-ico", layer: "atom", name: "Row Ico" },
  pcLibCaret: { id: "pico.pcLib-caret", layer: "atom", name: "Caret" },
  pcLibQueryText: {
    id: "pico.pcLib-query-text",
    layer: "atom",
    name: "Query Text",
  },
  pcTab: { id: "pico.pc-tab", layer: "atom", name: "Tab" },
} as const satisfies Record<string, PicoDesignPart>

export function picoDesignPartAttrs(
  part: PicoDesignPart,
  instanceId?: string,
): Record<string, string> {
  return {
    "data-korri-part": part.id,
    "data-korri-layer": part.layer,
    "data-korri-name": part.name,
    ...(instanceId ? { "data-korri-instance-id": instanceId } : {}),
  }
}
