# Bun configuration file
# https://bun.sh/docs/runtime/bunfig

[test]
root = "./"
pattern = ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx"]
preload = ["./tools/testing/mock-import-meta.ts", "./tools/testing/happydom.ts", "./tools/testing/testing-library.ts", "./tools/testing/setup-global.ts"]
smol = true
bail = 0
coverage = false
coverageReporter = ["text", "lcov"]
coverageThreshold = { lines = 80 }
timeout = 10000

[test.env]
NODE_ENV = "test"

[install]
production = false

[install.lockfile]
save = true

[develop]
port = 3000
