#!/usr/bin/env bash
# One-time bootstrap of the AYN Odin 2 Portal for the Korri iterative loop.
#
# Idempotent: re-running upgrades Bun, re-syncs the project, and refreshes
# /storage/korri/.env from the live EmulationStation environment without
# disturbing a running tmux session.
#
# See docs/development/odin-iterative-loop.md.

set -euo pipefail

ODIN_HOST="${ODIN_HOST:-root@sm8550}"
ODIN_PROJECT="${ODIN_PROJECT:-/storage/korri}"

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

log()  { printf '\033[0;36m[odin-bootstrap]\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[0;31m[odin-bootstrap]\033[0m %s\n' "$*" >&2; exit 1; }

# 1. Reachability ------------------------------------------------------------
log "Probing $ODIN_HOST..."
ssh -o ConnectTimeout=5 -o BatchMode=yes "$ODIN_HOST" 'echo ok' >/dev/null \
  || fail "Cannot reach $ODIN_HOST. Check SSH key auth and Tailscale connectivity."

# 2. Bun ---------------------------------------------------------------------
log "Ensuring Bun under /storage/bin/bun..."
ssh "$ODIN_HOST" 'bash -s' <<'REMOTE'
set -euo pipefail
mkdir -p /storage/bin
need_install=1
if [ -x /storage/bin/bun ]; then
  if /storage/bin/bun --version >/dev/null 2>&1; then
    need_install=0
  fi
fi
if [ "$need_install" = "1" ]; then
  echo "Downloading Bun aarch64..."
  cd /tmp
  rm -rf bun-linux-aarch64 bun-linux-aarch64.zip
  curl -fsSL -o bun-linux-aarch64.zip \
    https://github.com/oven-sh/bun/releases/latest/download/bun-linux-aarch64.zip
  if command -v unzip >/dev/null 2>&1; then
    unzip -q bun-linux-aarch64.zip
  else
    busybox unzip -q bun-linux-aarch64.zip
  fi
  install -m 0755 bun-linux-aarch64/bun /storage/bin/bun
  rm -rf bun-linux-aarch64 bun-linux-aarch64.zip
fi
echo "bun: $(/storage/bin/bun --version)"
REMOTE

# 3. /storage/.profile PATH --------------------------------------------------
log "Ensuring /storage/.profile puts /storage/bin and nix on PATH..."
ssh "$ODIN_HOST" 'bash -s' <<'REMOTE'
set -euo pipefail
profile=/storage/.profile
marker='# korri:bin-path'
touch "$profile"
if ! grep -qF "$marker" "$profile" 2>/dev/null; then
  {
    echo ""
    echo "$marker"
    echo 'export PATH="/storage/bin:/storage/.nix-profile/bin:$PATH"'
  } >> "$profile"
fi
REMOTE

# 4. Project rsync -----------------------------------------------------------
log "Syncing project to $ODIN_HOST:$ODIN_PROJECT..."
ssh "$ODIN_HOST" "mkdir -p '$ODIN_PROJECT'"
rsync -az --delete \
  --exclude=node_modules \
  --exclude=out \
  --exclude=.worktrees \
  --exclude=.direnv \
  --exclude=.tanstack \
  --exclude=.git \
  --exclude=.nix-bin \
  --exclude=.env \
  --exclude=media \
  "$REPO_ROOT/" "$ODIN_HOST:$ODIN_PROJECT/"

# 5. bun install -------------------------------------------------------------
log "Running bun install on the device (aarch64-native dependencies)..."
ssh "$ODIN_HOST" "cd '$ODIN_PROJECT' && /storage/bin/bun install"

# 6. Harvest Wayland env from running emulationstation -----------------------
log "Harvesting Wayland session env from emulationstation..."
es_env="$(ssh "$ODIN_HOST" 'bash -s' <<'REMOTE'
set -euo pipefail
es_pid="$(pgrep -f emulationstation | head -1 || true)"
if [ -z "$es_pid" ]; then
  echo "ES_NOT_RUNNING" >&2
  exit 2
fi
cat "/proc/$es_pid/environ" \
  | tr '\0' '\n' \
  | grep -E '^(WAYLAND_DISPLAY|XDG_RUNTIME_DIR|DISPLAY|DBUS_SESSION_BUS_ADDRESS|XDG_SESSION_TYPE)='
REMOTE
)" || fail "EmulationStation is not running on the device. Boot ROCKNIX so its Wayland session is alive, then re-run \`just bootstrap-odin\`. Or hand-write $ODIN_PROJECT/.env with WAYLAND_DISPLAY/XDG_RUNTIME_DIR before continuing."

if [ -z "$es_env" ]; then
  fail "Could not read Wayland env from emulationstation (/proc env empty). Restart ES and retry."
fi

log "Writing $ODIN_PROJECT/.env..."
ssh "$ODIN_HOST" "cat > '$ODIN_PROJECT/.env'" <<EOF
# Generated by tools/scripts/odin-bootstrap.sh on $(date -u +%FT%TZ).
# Wayland session env harvested from the live emulationstation process so
# children of \`runemu.sh\` (the actual emulators) render to the handheld
# screen instead of the SSH session's nowhere-display.
$es_env
# Korri runtime config — gamelist roots that ROCKNIX actually populates on
# this device. The default rocknix-source roots
# (/storage/games-internal/roms, /storage/games-external/roms) miss most of
# the user's library because /storage/roms/ is the unified mount that
# EmulationStation scans.
KORRI_ROCKNIX_GAMELIST_ROOTS=/storage/roms
EOF

log "Bootstrap complete."
log "Next: \`just dev-odin\`."
