import { readFileSync } from "node:fs"

export const productionBuildDependencyNames = [
  // Vite is a build-time tool for the production portal bundle. It lives in
  // devDependencies for local development, but Nix production builds invoke it
  // directly from node_modules/vite/bin/vite.js.
  "vite",
  "@vitejs/plugin-react",
]

const trailingCommaPattern = /,\s*([}\]])/g

export type BunLockPackage = [
  ident: string,
  registry: string,
  metadata?: {
    dependencies?: Record<string, string>
    optionalDependencies?: Record<string, string>
    peerDependencies?: Record<string, string>
  },
  integrity?: string,
]

export interface BunLockFile {
  workspaces: {
    "": {
      dependencies?: Record<string, string>
      devDependencies?: Record<string, string>
    }
  }
  packages: Record<string, BunLockPackage>
}

export function parseBunLock(lockText: string): BunLockFile {
  return JSON.parse(lockText.replace(trailingCommaPattern, "$1"))
}

function assertVersionedIdent(ident: string): string {
  const at = ident.lastIndexOf("@")
  if (at <= 0) {
    throw new Error(`Cannot derive bun.nix attr name from lock ident: ${ident}`)
  }
  return ident
}

function dependencyEdges(
  pkg: BunLockPackage,
): Array<{ name: string; required: boolean }> {
  const metadata = pkg[2] ?? {}
  return [
    ...Object.keys(metadata.dependencies ?? {}).map(name => ({
      name,
      required: true,
    })),
    ...Object.keys(metadata.optionalDependencies ?? {}).map(name => ({
      name,
      required: false,
    })),
    ...Object.keys(metadata.peerDependencies ?? {}).map(name => ({
      name,
      required: false,
    })),
  ]
}

function resolveDependencyKey(
  packages: Record<string, BunLockPackage>,
  parentKey: string,
  dependencyName: string,
): string | undefined {
  const nestedKey = `${parentKey}/${dependencyName}`
  if (packages[nestedKey]) return nestedKey
  if (packages[dependencyName]) return dependencyName

  const matchingKeys = Object.keys(packages).filter(key =>
    packages[key]?.[0]?.startsWith(`${dependencyName}@`),
  )

  if (matchingKeys.length === 1) return matchingKeys[0]

  return undefined
}

function productionDependencySpecMap(
  packageJsonText: string,
): Record<string, string> {
  const packageJson = JSON.parse(packageJsonText) as {
    dependencies?: Record<string, string>
    devDependencies?: Record<string, string>
  }
  const dependencies: Record<string, string> = {
    ...(packageJson.dependencies ?? {}),
  }
  const missingBuildDeps = productionBuildDependencyNames.filter(
    name =>
      !packageJson.dependencies?.[name] && !packageJson.devDependencies?.[name],
  )
  if (missingBuildDeps.length > 0) {
    throw new Error(
      `Production build dependency names missing from package.json: ${missingBuildDeps.join(", ")}`,
    )
  }
  for (const name of productionBuildDependencyNames) {
    const devDependency = packageJson.devDependencies?.[name]
    if (!dependencies[name] && !devDependency) {
      throw new Error(
        `Cannot promote missing production build dependency: ${name}`,
      )
    }
    dependencies[name] = dependencies[name] ?? devDependency
  }
  return Object.fromEntries(Object.entries(dependencies).sort())
}

export function productionRootDependencyNames(
  packageJsonText: string,
): string[] {
  return Object.keys(productionDependencySpecMap(packageJsonText)).sort()
}

export function productionBunPackageNames(
  lock: BunLockFile,
  rootDependencyNames: string[],
): string[] {
  const seenLockKeys = new Set<string>()
  const seenPackageNames = new Set<string>()
  const queue = [...rootDependencyNames]

  while (queue.length > 0) {
    const lockKey = queue.shift()
    if (!lockKey) continue
    const pkg = lock.packages[lockKey]
    if (!pkg) {
      throw new Error(
        `Root production dependency ${lockKey} is absent from bun.lock packages`,
      )
    }
    if (seenLockKeys.has(lockKey)) continue
    seenLockKeys.add(lockKey)
    seenPackageNames.add(assertVersionedIdent(pkg[0]))

    for (const dep of dependencyEdges(pkg)) {
      const resolved = resolveDependencyKey(lock.packages, lockKey, dep.name)
      if (resolved) {
        queue.push(resolved)
      } else if (dep.required) {
        throw new Error(
          `Could not resolve required dependency ${dep.name} from ${lockKey}`,
        )
      }
    }
  }

  return [...seenPackageNames].sort()
}

export function renderNixStringList(names: string[]): string {
  const lines = names.map(name => `  ${JSON.stringify(name)}`)
  return `# Generated by tools/nix/bun-production-deps.ts.\n# Runtime/build-time Bun packages needed by production Korri Nix builds.\n[\n${lines.join("\n")}\n]\n`
}

export function productionPackageJson(packageJsonText: string): string {
  const packageJson = JSON.parse(packageJsonText) as {
    name?: string
    private?: boolean
    version?: string
    dependencies?: Record<string, string>
    devDependencies?: Record<string, string>
  }
  return `${JSON.stringify(
    {
      name: packageJson.name,
      private: packageJson.private,
      version: packageJson.version,
      dependencies: productionDependencySpecMap(packageJsonText),
    },
    null,
    2,
  )}\n`
}

export function productionBunLock(
  lockText: string,
  packageJsonText: string,
): string {
  const lock = parseBunLock(lockText) as BunLockFile
  lock.workspaces[""].dependencies =
    productionDependencySpecMap(packageJsonText)
  delete lock.workspaces[""].devDependencies
  return `${JSON.stringify(lock, null, 2)}\n`
}

if (import.meta.main) {
  const mode = process.argv[2] ?? "names"
  const packageJsonText = readFileSync("package.json", "utf8")
  if (mode === "package-json") {
    process.stdout.write(productionPackageJson(packageJsonText))
  } else if (mode === "bun-lock") {
    process.stdout.write(
      productionBunLock(readFileSync("bun.lock", "utf8"), packageJsonText),
    )
  } else if (mode === "names") {
    const lock = parseBunLock(readFileSync("bun.lock", "utf8"))
    const roots = productionRootDependencyNames(packageJsonText)
    process.stdout.write(
      renderNixStringList(productionBunPackageNames(lock, roots)),
    )
  } else {
    throw new Error(`Unknown mode: ${mode}`)
  }
}
