use super::{AndroidComponent, FileProvisionMode, LaunchSpec, LocalGame, ProvisionedFile};
use std::{collections::HashMap, fs, path::Path};

#[derive(Debug, thiserror::Error)]
pub enum LaunchError {
    #[error("unknown local game: {0}")]
    UnknownGame(String),
    #[error("local ROM is missing: {0}")]
    RomMissing(String),
    #[error("local storage is unavailable: {0}")]
    StorageAccess(String),
    #[error("failed to provision RetroArch config: {0}")]
    Config(String),
}

pub fn local_games() -> Vec<LocalGame> {
    vec![LocalGame {
        id: "wl4".into(),
        title: "Wario Land 4".into(),
        system: "Game Boy Advance".into(),
    }]
}

fn config_content(root: &Path) -> String {
    format!(
        r#"# generated by Korri
libretro_directory = "/data/data/com.korri.retroarch/cores"
system_directory = "{system}"
savefile_directory = "{saves}"
savestate_directory = "{states}"
screenshot_directory = "{screenshots}"

# invisible RetroArch: no menu reachable, no overlay
kiosk_mode_enable = "true"
input_menu_toggle_gamepad_combo = "0"
input_menu_toggle = "nul"
input_overlay_enable = "false"
video_font_enable = "true"

# Korri owns lifecycle and config
quit_on_close_content = "true"
quit_press_twice = "false"
config_save_on_exit = "false"
pause_nonactive = "true"

# persistence
savestate_auto_save = "true"
savestate_auto_load = "true"
autosave_interval = "10"

# features retained from stock RetroArch
rewind_enable = "true"
run_ahead_enabled = "true"
run_ahead_frames = "1"
run_ahead_secondary_instance = "true"

# stock Vulkan crashes on Mali/Immortalis
video_driver = "gl"

"#,
        system = root.join("system").display(),
        saves = root.join("saves").display(),
        states = root.join("states").display(),
        screenshots = root.join("screenshots").display(),
    )
}

pub fn launch_game(
    root: &Path,
    game_id: &str,
    provision_mode: FileProvisionMode,
) -> Result<LaunchSpec, LaunchError> {
    if game_id != "wl4" {
        return Err(LaunchError::UnknownGame(game_id.into()));
    }
    let rom = root.join("roms/wl4.gba");
    match fs::metadata(&rom) {
        Ok(metadata) if metadata.is_file() => {}
        Ok(_) => return Err(LaunchError::RomMissing(rom.display().to_string())),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Err(LaunchError::RomMissing(rom.display().to_string()));
        }
        Err(error) => return Err(LaunchError::StorageAccess(error.to_string())),
    }

    let config = root.join("retroarch.cfg");
    let content = config_content(root);
    let provisioned_directories = ["system", "saves", "states", "screenshots"];
    let (directories, files) = match provision_mode {
        FileProvisionMode::Direct => {
            for directory in provisioned_directories {
                fs::create_dir_all(root.join(directory))
                    .map_err(|error| LaunchError::Config(error.to_string()))?;
            }
            fs::write(&config, &content).map_err(|error| LaunchError::Config(error.to_string()))?;
            (Vec::new(), Vec::new())
        }
        FileProvisionMode::Deferred => (
            provisioned_directories
                .into_iter()
                .map(|directory| root.join(directory).display().to_string())
                .collect(),
            vec![ProvisionedFile {
                path: config.display().to_string(),
                content,
            }],
        ),
    };

    Ok(LaunchSpec {
        launcher_id: "retroarch".into(),
        component: AndroidComponent {
            package_name: "com.korri.retroarch".into(),
            class_name: "com.retroarch.browser.retroactivity.RetroActivityFuture".into(),
        },
        extras: HashMap::from([
            ("ROM".into(), rom.display().to_string()),
            (
                "LIBRETRO".into(),
                "/data/data/com.korri.retroarch/cores/mgba_libretro_android.so".into(),
            ),
            ("CONFIGFILE".into(), config.display().to_string()),
        ]),
        directories,
        files,
        integrity: String::new(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root_with_rom() -> tempfile::TempDir {
        let root = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(root.path().join("roms")).unwrap();
        std::fs::write(root.path().join("roms/wl4.gba"), b"rom").unwrap();
        root
    }

    #[test]
    fn lists_the_single_wario_land_4_entry() {
        assert_eq!(
            local_games(),
            vec![LocalGame {
                id: "wl4".into(),
                title: "Wario Land 4".into(),
                system: "Game Boy Advance".into(),
            }]
        );
    }

    #[test]
    fn launches_wario_land_with_paths_rooted_in_korri_storage() {
        let root = root_with_rom();

        let spec = launch_game(root.path(), "wl4", FileProvisionMode::Direct).expect("launch spec");

        assert_eq!(spec.launcher_id, "retroarch");
        assert_eq!(spec.component.package_name, "com.korri.retroarch");
        assert_eq!(
            spec.component.class_name,
            "com.retroarch.browser.retroactivity.RetroActivityFuture"
        );
        assert_eq!(
            spec.extras.get("ROM").map(String::as_str),
            Some(root.path().join("roms/wl4.gba").to_str().unwrap())
        );
        assert_eq!(
            spec.extras.get("LIBRETRO").map(String::as_str),
            Some("/data/data/com.korri.retroarch/cores/mgba_libretro_android.so")
        );
        assert_eq!(
            spec.extras.get("CONFIGFILE").map(String::as_str),
            Some(root.path().join("retroarch.cfg").to_str().unwrap())
        );
        assert!(!spec.extras.contains_key("QUITFOCUS"));
        assert!(spec.files.is_empty());
        let config = std::fs::read_to_string(root.path().join("retroarch.cfg")).unwrap();
        assert!(config.contains("video_driver = \"gl\""));
    }

    #[test]
    fn defers_config_bytes_to_the_android_storage_edge_without_mutating() {
        let root = root_with_rom();
        let config = root.path().join("retroarch.cfg");
        std::fs::write(&config, b"existing config").unwrap();

        let spec =
            launch_game(root.path(), "wl4", FileProvisionMode::Deferred).expect("deferred spec");

        assert_eq!(std::fs::read(&config).unwrap(), b"existing config");
        assert_eq!(
            spec.directories,
            ["system", "saves", "states", "screenshots"].map(|directory| root
                .path()
                .join(directory)
                .display()
                .to_string())
        );
        assert!(spec
            .directories
            .iter()
            .all(|directory| !std::path::Path::new(directory).exists()));
        assert_eq!(spec.files.len(), 1);
        assert_eq!(spec.files[0].path, config.display().to_string());
        assert!(spec.files[0].content.contains("video_driver = \"gl\""));
        assert!(spec.files[0]
            .content
            .contains("kiosk_mode_enable = \"true\""));
    }

    #[test]
    fn deterministically_provisions_the_kiosk_config_and_save_tree() {
        let root = root_with_rom();
        std::fs::write(root.path().join("retroarch.cfg"), b"user setting").unwrap();

        launch_game(root.path(), "wl4", FileProvisionMode::Direct).expect("launch spec");

        let config = std::fs::read_to_string(root.path().join("retroarch.cfg")).unwrap();
        assert!(config.contains("video_driver = \"gl\""));
        assert!(config.contains("kiosk_mode_enable = \"true\""));
        assert!(config.contains("autosave_interval = \"10\""));
        assert!(config.contains("quit_press_twice = \"false\""));
        assert!(config.contains(&format!(
            "savefile_directory = \"{}\"",
            root.path().join("saves").display()
        )));
        assert!(!config.contains("QUITFOCUS"));
        for directory in ["system", "saves", "states", "screenshots"] {
            assert!(root.path().join(directory).is_dir(), "missing {directory}");
        }
    }

    #[test]
    fn rejects_missing_rom_and_unknown_game_with_distinct_errors() {
        let root = tempfile::tempdir().unwrap();
        assert!(matches!(
            launch_game(root.path(), "wl4", FileProvisionMode::Direct),
            Err(LaunchError::RomMissing(_))
        ));
        assert!(matches!(
            launch_game(root.path(), "unknown", FileProvisionMode::Direct),
            Err(LaunchError::UnknownGame(_))
        ));
    }

    #[cfg(unix)]
    #[test]
    fn distinguishes_unreadable_storage_from_a_missing_rom() {
        use std::os::unix::fs::PermissionsExt;

        let root = root_with_rom();
        std::fs::set_permissions(root.path(), std::fs::Permissions::from_mode(0o000)).unwrap();
        let result = launch_game(root.path(), "wl4", FileProvisionMode::Direct);
        std::fs::set_permissions(root.path(), std::fs::Permissions::from_mode(0o700)).unwrap();

        assert!(matches!(result, Err(LaunchError::StorageAccess(_))));
    }
}
