use super::{AndroidComponent, FileProvisionMode, LaunchError, LaunchSpec, ProvisionedFile};
use crate::config::resolver::ResolvedRoute;
use std::{
    collections::HashMap,
    fs::{self, OpenOptions},
    io::Write,
    path::{Component, Path},
};

const RETROARCH_PROVIDER: &str = "@korri:retroarch";
const RETROARCH_LAUNCHER: &str = "@korri:retroarch/retroarch";
const RETROARCH_TOKEN: &str = "retroarch";
const LIBRETRO_CORE_KIND: &str = "libretro-core";
const ANDROID_ROM_STORAGE: &str = "roms";

fn config_content(root: &Path, libretro_directory: &Path) -> String {
    format!(
        r#"# generated by Korri
libretro_directory = "{libretro_directory}"
system_directory = "{system}"
savefile_directory = "{saves}"
savestate_directory = "{states}"
screenshot_directory = "{screenshots}"

# invisible RetroArch: no menu reachable, no overlay
kiosk_mode_enable = "true"
input_menu_toggle_gamepad_combo = "0"
input_menu_toggle = "nul"
input_overlay_enable = "false"
video_font_enable = "true"

# Korri owns lifecycle and config
quit_on_close_content = "true"
quit_press_twice = "false"
config_save_on_exit = "false"
pause_nonactive = "true"
log_verbosity = "true"

# persistence
savestate_auto_save = "true"
savestate_auto_load = "true"
autosave_interval = "10"

# features retained from stock RetroArch
rewind_enable = "true"
run_ahead_enabled = "true"
run_ahead_frames = "1"
run_ahead_secondary_instance = "true"

# stock Vulkan crashes on Mali/Immortalis
video_driver = "gl"

"#,
        libretro_directory = libretro_directory.display(),
        system = root.join("system").display(),
        saves = root.join("saves").display(),
        states = root.join("states").display(),
        screenshots = root.join("screenshots").display(),
    )
}

fn write_atomically(path: &Path, content: &[u8]) -> std::io::Result<()> {
    let parent = path.parent().ok_or_else(|| {
        std::io::Error::new(std::io::ErrorKind::InvalidInput, "config has no parent")
    })?;
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            std::io::Error::new(std::io::ErrorKind::InvalidInput, "invalid config name")
        })?;
    let temporary = parent.join(format!(".{file_name}.{:016x}.tmp", rand::random::<u64>()));
    let result = (|| {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)?;
        file.write_all(content)?;
        file.sync_all()?;
        fs::rename(&temporary, path)?;
        fs::File::open(parent)?.sync_all()?;
        Ok(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result
}

pub fn validate_route(route: &ResolvedRoute) -> Result<(), LaunchError> {
    if route.provider_id != RETROARCH_PROVIDER
        || route.launcher_kind != RETROARCH_PROVIDER
        || route.launcher_id != RETROARCH_LAUNCHER
        || route.integration_token != RETROARCH_TOKEN
    {
        return Err(LaunchError::RouteUnavailable(format!(
            "route {} is not owned by the RetroArch plugin",
            route.playable_id
        )));
    }
    route.android_component.as_ref().ok_or_else(|| {
        LaunchError::RouteUnavailable(format!(
            "RetroArch route {} has no plugin-provided Android component",
            route.playable_id
        ))
    })?;
    let runtime = route.runtime.as_ref().ok_or_else(|| {
        LaunchError::RouteUnavailable(format!(
            "RetroArch route {} has no plugin-provided runtime",
            route.playable_id
        ))
    })?;
    if runtime.kind != LIBRETRO_CORE_KIND || runtime.app != route.launcher_id {
        return Err(LaunchError::RouteUnavailable(format!(
            "runtime {} is incompatible with launcher {}",
            runtime.id, route.launcher_id
        )));
    }
    let target = route.file_target.as_ref().ok_or_else(|| {
        LaunchError::RouteUnavailable(format!(
            "RetroArch route {} has no file target",
            route.playable_id
        ))
    })?;
    if target.storage_id != ANDROID_ROM_STORAGE {
        return Err(LaunchError::RouteUnavailable(format!(
            "RetroArch route {} uses unsupported Android storage {}",
            route.playable_id, target.storage_id
        )));
    }
    if Path::new(&target.path)
        .components()
        .any(|component| !matches!(component, Component::Normal(_)))
    {
        return Err(LaunchError::RouteUnavailable(format!(
            "RetroArch route {} has an unsafe file target",
            route.playable_id
        )));
    }
    Ok(())
}

pub fn launch_route(
    root: &Path,
    route: &ResolvedRoute,
    provision_mode: FileProvisionMode,
) -> Result<LaunchSpec, LaunchError> {
    validate_route(route)?;
    let component = route
        .android_component
        .as_ref()
        .expect("validated component");
    let runtime = route.runtime.as_ref().expect("validated runtime");
    let target = route.file_target.as_ref().expect("validated file target");
    let relative_rom = Path::new(&target.path);
    let rom = root.join(ANDROID_ROM_STORAGE).join(relative_rom);
    match fs::metadata(&rom) {
        Ok(metadata) if metadata.is_file() => {}
        Ok(_) => return Err(LaunchError::RomMissing(rom.display().to_string())),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Err(LaunchError::RomMissing(rom.display().to_string()));
        }
        Err(error) => return Err(LaunchError::StorageAccess(error.to_string())),
    }

    let libretro_directory = Path::new(&runtime.path).parent().ok_or_else(|| {
        LaunchError::RouteUnavailable(format!(
            "runtime {} has no containing core directory",
            runtime.id
        ))
    })?;
    let config = root.join("retroarch.cfg");
    let content = config_content(root, libretro_directory);
    let provisioned_directories = ["system", "saves", "states", "screenshots"];
    let (directories, files) = match provision_mode {
        FileProvisionMode::Direct => {
            for directory in provisioned_directories {
                fs::create_dir_all(root.join(directory))
                    .map_err(|error| LaunchError::Config(error.to_string()))?;
            }
            write_atomically(&config, content.as_bytes())
                .map_err(|error| LaunchError::Config(error.to_string()))?;
            (Vec::new(), Vec::new())
        }
        FileProvisionMode::Deferred => (
            provisioned_directories
                .into_iter()
                .map(|directory| root.join(directory).display().to_string())
                .collect(),
            vec![ProvisionedFile {
                path: config.display().to_string(),
                content,
            }],
        ),
    };

    Ok(LaunchSpec {
        launcher_id: route.integration_token.clone(),
        component: AndroidComponent {
            package_name: component.package_name.clone(),
            class_name: component.class_name.clone(),
        },
        extras: HashMap::from([
            ("ROM".into(), rom.display().to_string()),
            ("LIBRETRO".into(), runtime.path.clone()),
            ("CONFIGFILE".into(), config.display().to_string()),
        ]),
        directories,
        files,
        integrity: String::new(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root_with_rom() -> tempfile::TempDir {
        let root = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(root.path().join("roms")).unwrap();
        std::fs::write(root.path().join("roms/wl4.gba"), b"rom").unwrap();
        root
    }

    fn route() -> ResolvedRoute {
        ResolvedRoute {
            playable_id: "wl4".into(),
            title: Some("Wario Land 4".into()),
            release_id: "gba".into(),
            provider_id: RETROARCH_PROVIDER.into(),
            system_id: "gba".into(),
            system_title: Some("Game Boy Advance".into()),
            launcher_id: RETROARCH_LAUNCHER.into(),
            launcher_kind: RETROARCH_PROVIDER.into(),
            integration_token: RETROARCH_TOKEN.into(),
            flattened_target: "roms:wl4.gba".into(),
            android_component: Some(crate::config::resolver::ResolvedAndroidComponent {
                package_name: "com.korri.retroarch".into(),
                class_name: "com.retroarch.browser.retroactivity.RetroActivityFuture".into(),
            }),
            linux_launcher: None,
            runtime: Some(crate::config::resolver::ResolvedRuntime {
                id: "@korri:mgba/mgba".into(),
                kind: LIBRETRO_CORE_KIND.into(),
                app: RETROARCH_LAUNCHER.into(),
                path: "/plugin/owned/mgba_libretro_android.so".into(),
                linux_path_env: None,
            }),
            file_target: Some(crate::config::resolver::ResolvedFileTarget {
                storage_id: ANDROID_ROM_STORAGE.into(),
                path: "wl4.gba".into(),
            }),
        }
    }

    #[test]
    fn launches_wario_land_with_paths_rooted_in_korri_storage() {
        let root = root_with_rom();

        let spec =
            launch_route(root.path(), &route(), FileProvisionMode::Direct).expect("launch spec");

        assert_eq!(spec.launcher_id, "retroarch");
        assert_eq!(spec.component.package_name, "com.korri.retroarch");
        assert_eq!(
            spec.component.class_name,
            "com.retroarch.browser.retroactivity.RetroActivityFuture"
        );
        assert_eq!(
            spec.extras.get("ROM").map(String::as_str),
            Some(root.path().join("roms/wl4.gba").to_str().unwrap())
        );
        assert_eq!(
            spec.extras.get("LIBRETRO").map(String::as_str),
            Some("/plugin/owned/mgba_libretro_android.so")
        );
        assert_eq!(
            spec.extras.get("CONFIGFILE").map(String::as_str),
            Some(root.path().join("retroarch.cfg").to_str().unwrap())
        );
        assert!(!spec.extras.contains_key("QUITFOCUS"));
        assert!(spec.files.is_empty());
        let config = std::fs::read_to_string(root.path().join("retroarch.cfg")).unwrap();
        assert!(config.contains("video_driver = \"gl\""));
    }

    #[test]
    fn defers_config_bytes_to_the_android_storage_edge_without_mutating() {
        let root = root_with_rom();
        let config = root.path().join("retroarch.cfg");
        std::fs::write(&config, b"existing config").unwrap();

        let spec = launch_route(root.path(), &route(), FileProvisionMode::Deferred)
            .expect("deferred spec");

        assert_eq!(std::fs::read(&config).unwrap(), b"existing config");
        assert_eq!(
            spec.directories,
            ["system", "saves", "states", "screenshots"].map(|directory| root
                .path()
                .join(directory)
                .display()
                .to_string())
        );
        assert!(spec
            .directories
            .iter()
            .all(|directory| !std::path::Path::new(directory).exists()));
        assert_eq!(spec.files.len(), 1);
        assert_eq!(spec.files[0].path, config.display().to_string());
        assert!(spec.files[0].content.contains("video_driver = \"gl\""));
        assert!(spec.files[0]
            .content
            .contains("kiosk_mode_enable = \"true\""));
    }

    #[cfg(unix)]
    #[test]
    fn direct_provisioning_atomically_replaces_a_config_symlink() {
        use std::os::unix::fs::symlink;

        let root = root_with_rom();
        let outside = root.path().join("outside-user-file");
        std::fs::write(&outside, b"do not replace").unwrap();
        symlink(&outside, root.path().join("retroarch.cfg")).unwrap();

        launch_route(root.path(), &route(), FileProvisionMode::Direct).expect("launch spec");

        assert_eq!(std::fs::read(&outside).unwrap(), b"do not replace");
        assert!(!root.path().join("retroarch.cfg").is_symlink());
        assert!(std::fs::read_to_string(root.path().join("retroarch.cfg"))
            .unwrap()
            .contains("kiosk_mode_enable = \"true\""));
    }

    #[test]
    fn deterministically_provisions_the_kiosk_config_and_save_tree() {
        let root = root_with_rom();
        std::fs::write(root.path().join("retroarch.cfg"), b"user setting").unwrap();

        launch_route(root.path(), &route(), FileProvisionMode::Direct).expect("launch spec");

        let config = std::fs::read_to_string(root.path().join("retroarch.cfg")).unwrap();
        assert!(config.contains("video_driver = \"gl\""));
        assert!(config.contains("kiosk_mode_enable = \"true\""));
        assert!(config.contains("autosave_interval = \"10\""));
        assert!(config.contains("log_verbosity = \"true\""));
        assert!(config.contains("quit_press_twice = \"false\""));
        assert!(config.contains(&format!(
            "savefile_directory = \"{}\"",
            root.path().join("saves").display()
        )));
        assert!(!config.contains("QUITFOCUS"));
        for directory in ["system", "saves", "states", "screenshots"] {
            assert!(root.path().join(directory).is_dir(), "missing {directory}");
        }
    }

    #[test]
    fn rejects_missing_rom_and_unsafe_file_targets() {
        let root = tempfile::tempdir().unwrap();
        assert!(matches!(
            launch_route(root.path(), &route(), FileProvisionMode::Direct),
            Err(LaunchError::RomMissing(_))
        ));

        let mut unsafe_route = route();
        unsafe_route.file_target.as_mut().unwrap().path = "../outside.gba".into();
        assert!(matches!(
            launch_route(root.path(), &unsafe_route, FileProvisionMode::Direct),
            Err(LaunchError::RouteUnavailable(_))
        ));
    }

    #[cfg(unix)]
    #[test]
    fn distinguishes_unreadable_storage_from_a_missing_rom() {
        use std::os::unix::fs::PermissionsExt;

        let root = root_with_rom();
        std::fs::set_permissions(root.path(), std::fs::Permissions::from_mode(0o000)).unwrap();
        let result = launch_route(root.path(), &route(), FileProvisionMode::Direct);
        std::fs::set_permissions(root.path(), std::fs::Permissions::from_mode(0o700)).unwrap();

        assert!(matches!(result, Err(LaunchError::StorageAccess(_))));
    }
}
