set working-directory := "../.."

push-zao:
    nix develop .#korrid --command ./services/korrid/deploy/push-zao.sh

restart-zao:
    nix develop .#korrid --command ./services/korrid/deploy/control-zao.sh restart

logs-zao:
    nix develop .#korrid --command ./services/korrid/deploy/control-zao.sh logs
