import { describe, expect, it } from "bun:test"
import { mkdtemp, readFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import {
  renderThreeDSenRomRegistry,
  writeThreeDSenRomRegistry,
} from "./rom-registry"

describe("3dSen ROM registry", () => {
  it("renders multiple profile mappings in the live Warning plus Items shape", () => {
    expect(
      renderThreeDSenRomRegistry([
        { id: "37", title: "Super Mario Bros.", romPath: "/roms/smb.nes" },
        { id: "47", title: "2D Mode", romPath: "/roms/2d.nes", lastTime: 12 },
      ]),
    ).toEqual({
      Warning: "Generated by Korri. Edit Korri config instead of this file.",
      Items: [
        {
          id: "37",
          title: "Super Mario Bros.",
          romPath: "/roms/smb.nes",
          lastTime: 0,
        },
        {
          id: "47",
          title: "2D Mode",
          romPath: "/roms/2d.nes",
          lastTime: 12,
        },
      ],
    })
  })

  it("writes the registry atomically to nested config directories", async () => {
    const root = await mkdtemp(join(tmpdir(), "korri-3dsen-registry-"))
    const path = join(root, "unity3d", "Geod Studio", "3dSen", "rom.json")
    await writeThreeDSenRomRegistry({
      path,
      profiles: [
        { id: "37", title: "Super Mario Bros.", romPath: "/roms/smb one.nes" },
      ],
    })

    expect(JSON.parse(await readFile(path, "utf8"))).toMatchObject({
      Items: [{ id: "37", romPath: "/roms/smb one.nes" }],
    })
  })
})
