import { mkdir, rename, writeFile } from "node:fs/promises"
import { dirname } from "node:path"

export interface ThreeDSenProfileMapping {
  readonly id: string
  readonly title: string
  readonly romPath: string
  readonly lastTime?: number
}

export interface ThreeDSenRomRegistry {
  readonly Warning: string
  readonly Items: readonly ThreeDSenRomRegistryItem[]
}

export interface ThreeDSenRomRegistryItem {
  readonly id: string
  readonly title: string
  readonly romPath: string
  readonly lastTime: number
}

export const DEFAULT_3DSEN_ROM_REGISTRY_WARNING =
  "Generated by Korri. Edit Korri config instead of this file."

export function renderThreeDSenRomRegistry(
  profiles: readonly ThreeDSenProfileMapping[],
): ThreeDSenRomRegistry {
  return {
    Warning: DEFAULT_3DSEN_ROM_REGISTRY_WARNING,
    Items: profiles.map(profile => ({
      id: profile.id,
      title: profile.title,
      romPath: profile.romPath,
      lastTime: profile.lastTime ?? 0,
    })),
  }
}

export async function writeThreeDSenRomRegistry(input: {
  readonly path: string
  readonly profiles: readonly ThreeDSenProfileMapping[]
}): Promise<void> {
  const registry = renderThreeDSenRomRegistry(input.profiles)
  await mkdir(dirname(input.path), { recursive: true })
  const tmp = `${input.path}.tmp-${process.pid}-${Date.now()}`
  await writeFile(tmp, `${JSON.stringify(registry, null, 2)}\n`, "utf8")
  await rename(tmp, input.path)
}
