#!/usr/bin/env bash
# Idempotently install/update everything Korri needs on the AYN Odin 2 Portal.
#
# Re-running this script ensures Bun, PATH setup, the synced project,
# aarch64-native dependencies, Wayland runtime env, the Korri session toggle
# command, and the Korri input daemon service are present and current.
#
# See docs/development/odin-iterative-loop.md.

set -euo pipefail

ODIN_HOST="${ODIN_HOST:-root@sm8550}"
ODIN_PROJECT="${ODIN_PROJECT:-/storage/korri}"
ODIN_INPUT_BRIDGE_PORT="${ODIN_INPUT_BRIDGE_PORT:-3002}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

log()  { printf '\033[0;36m[odin-install]\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[0;31m[odin-install]\033[0m %s\n' "$*" >&2; exit 1; }

read -r -a SSH_EXTRA_OPTS <<< "${ODIN_SSH_OPTS:-}"
RSYNC_SSH=(ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new "${SSH_EXTRA_OPTS[@]}")

ssh_odin() {
  ssh \
    -o ConnectTimeout=5 \
    -o BatchMode=yes \
    -o StrictHostKeyChecking=accept-new \
    "${SSH_EXTRA_OPTS[@]}" \
    "$ODIN_HOST" "$@"
}

# 1. Reachability ------------------------------------------------------------
log "Probing $ODIN_HOST..."
ssh_odin 'echo ok' >/dev/null \
  || fail "Cannot reach $ODIN_HOST. Check SSH key auth and Tailscale connectivity."

# 2. Bun ---------------------------------------------------------------------
log "Installing latest Bun under /storage/bin/bun..."
ssh_odin 'bash -s' <<'REMOTE'
set -euo pipefail
mkdir -p /storage/bin
cd /tmp
rm -rf bun-linux-aarch64 bun-linux-aarch64.zip
curl -fsSL -o bun-linux-aarch64.zip \
  https://github.com/oven-sh/bun/releases/latest/download/bun-linux-aarch64.zip
if command -v unzip >/dev/null 2>&1; then
  unzip -q bun-linux-aarch64.zip
else
  busybox unzip -q bun-linux-aarch64.zip
fi
install -m 0755 bun-linux-aarch64/bun /storage/bin/bun
rm -rf bun-linux-aarch64 bun-linux-aarch64.zip
echo "bun: $(/storage/bin/bun --version)"
REMOTE

# 3. /storage/.profile PATH --------------------------------------------------
log "Ensuring /storage/.profile puts /storage/bin and nix on PATH..."
ssh_odin 'bash -s' <<'REMOTE'
set -euo pipefail
profile=/storage/.profile
marker='# korri:bin-path'
touch "$profile"
if ! grep -qF "$marker" "$profile" 2>/dev/null; then
  {
    echo ""
    echo "$marker"
    echo 'export PATH="/storage/bin:/storage/.nix-profile/bin:$PATH"'
  } >> "$profile"
fi
REMOTE

# 4. Project rsync -----------------------------------------------------------
log "Syncing project to $ODIN_HOST:$ODIN_PROJECT..."
ssh_odin "mkdir -p '$ODIN_PROJECT'"
rsync -az --delete \
  -e "${RSYNC_SSH[*]}" \
  --exclude=node_modules \
  --exclude=out \
  --exclude=.worktrees \
  --exclude=.direnv \
  --exclude=.tanstack \
  --exclude=.git \
  --exclude=.nix-bin \
  --exclude=.env \
  --exclude=media \
  "$REPO_ROOT/" "$ODIN_HOST:$ODIN_PROJECT/"

# 5. bun install -------------------------------------------------------------
log "Running bun install on the device (aarch64-native dependencies)..."
ssh_odin "cd '$ODIN_PROJECT' && /storage/bin/bun install"

# 6. Harvest Wayland env from the live session -------------------------------
log "Harvesting Wayland session env from emulationstation or sway..."
es_env="$(ssh_odin 'bash -s' <<'REMOTE'
set -euo pipefail
session_pid="$(pgrep -f emulationstation | head -1 || true)"
if [ -z "$session_pid" ]; then
  session_pid="$(pgrep -x sway | head -1 || true)"
fi
if [ -z "$session_pid" ]; then
  session_pid="$(pgrep -f '/usr/bin/sway -V|/usr/bin/sway$|sway.sh' | head -1 || true)"
fi
if [ -z "$session_pid" ]; then
  echo "WAYLAND_SESSION_NOT_RUNNING" >&2
  exit 2
fi
cat "/proc/$session_pid/environ" \
  | tr '\0' '\n' \
  | grep -E '^(WAYLAND_DISPLAY|XDG_RUNTIME_DIR|DISPLAY|DBUS_SESSION_BUS_ADDRESS|XDG_SESSION_TYPE)='
REMOTE
)" || fail "No live ROCKNIX Wayland/Sway session env found. Start sway/EmulationStation or hand-write $ODIN_PROJECT/.env with WAYLAND_DISPLAY/XDG_RUNTIME_DIR before continuing."

if [ -z "$es_env" ]; then
  fail "Could not read Wayland env from the live session (/proc env empty). Restart Sway/ES and retry."
fi

log "Writing $ODIN_PROJECT/.env..."
ssh_odin "cat > '$ODIN_PROJECT/.env'" <<EOF
# Generated by scripts/odin/install.sh on $(date -u +%FT%TZ).
# Wayland session env harvested from the live emulationstation process so
# children of \`runemu.sh\` (the actual emulators) render to the handheld
# screen instead of the SSH session's nowhere-display.
$es_env
# Korri runtime config — gamelist roots that ROCKNIX actually populates on
# this device. The default rocknix-source roots
# (/storage/games-internal/roms, /storage/games-external/roms) miss most of
# the user's library because /storage/roms/ is the unified mount that
# EmulationStation scans.
KORRI_ROCKNIX_GAMELIST_ROOTS=/storage/roms
EOF

# 7. Korri session toggle command -------------------------------------------
log "Ensuring Korri session toggle command is installed..."
"$SCRIPT_DIR/install-korri-toggle.sh" install

# 8. Korri input daemon ------------------------------------------------------
log "Installing/restarting Korri input daemon service..."
ssh_odin "cd '$ODIN_PROJECT' && ODIN_PROJECT='$ODIN_PROJECT' ODIN_INPUT_BRIDGE_PORT='$ODIN_INPUT_BRIDGE_PORT' scripts/odin/install-inputd-service.sh install-start-mask"

# 9. Korri session supervisor ------------------------------------------------
log "Installing/restarting Korri session supervisor service..."
ssh_odin "cd '$ODIN_PROJECT' && ODIN_PROJECT='$ODIN_PROJECT' scripts/odin/install-sessiond-service.sh install-start"

log "Odin install/update complete."
log "Next: \`just dev-odin\`. Roll back input ownership with: ssh $ODIN_HOST '$ODIN_PROJECT/scripts/odin/install-inputd-service.sh rollback'"
log "Roll back Korri session supervision with: ssh $ODIN_HOST '$ODIN_PROJECT/scripts/odin/install-sessiond-service.sh rollback'"
