{ korri }:

{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.korri.kiosk;
  groupName = if cfg.group != null then cfg.group else cfg.user;
  runtimeDirectoryName = lib.removePrefix "/run/" cfg.runtimeDir;
  providerServices = cfg.input.provider.services;
  inputRequiredWithoutProvider =
    cfg.input.required && !(cfg.input.provider.enable) && cfg.input.optOutReason == null;

  inherit (lib)
    mkDefault
    mkEnableOption
    mkIf
    mkOption
    types
    ;

  clientCommand = cfg.client.command;
  swayConfig = pkgs.writeText "korri-kiosk-sway.conf" ''
    # Generated by services.korri.kiosk. Platform modules may append
    # display/input fragments through services.korri.kiosk.sway.extraConfig.
    set $korri_client ${lib.escapeShellArg clientCommand}
    exec --no-startup-id $korri_client

    ${cfg.sway.extraConfig}
  '';

  sessionEnvironment = cfg.environment // {
    HOME = cfg.home;
    XDG_RUNTIME_DIR = cfg.runtimeDir;
    XDG_STATE_HOME = cfg.stateHome;
    XDG_DATA_HOME = cfg.dataHome;
    XDG_CONFIG_HOME = cfg.configHome;
    KORRI_KIOSK = "1";
  };
in
{
  imports = [
    (import ./korri-client.nix { inherit korri; })
    (import ./korri-inputd.nix { inherit korri; })
  ];

  options.services.korri.kiosk = {
    enable = mkEnableOption "Korri appliance kiosk session";

    user = mkOption {
      type = types.str;
      default = "korri-kiosk";
      description = ''
        Unix user that owns the Korri kiosk compositor session. Platform
        adapters for constrained guests may set this to `root` only when they
        also set `createUser = false`.
      '';
    };

    group = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "Unix group for the Korri kiosk session. Defaults to `services.korri.kiosk.user`.";
    };

    createUser = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Create the configured kiosk user and group. Disable when a platform
        adapter supplies the user itself, including constrained guests that run
        the session as root.
      '';
    };

    home = mkOption {
      type = types.str;
      default = if cfg.user == "root" then "/root" else "/var/lib/korri-kiosk";
      description = "Home directory used by the kiosk session and Korri desktop wrapper.";
    };

    runtimeDir = mkOption {
      type = types.str;
      default = "/run/korri-kiosk";
      description = "Runtime directory exposed to the kiosk compositor as XDG_RUNTIME_DIR.";
    };

    stateHome = mkOption {
      type = types.str;
      default = "${cfg.home}/.local/state";
      description = "XDG state root for the kiosk session.";
    };

    dataHome = mkOption {
      type = types.str;
      default = "${cfg.home}/.local/share";
      description = "XDG data root for the kiosk session.";
    };

    configHome = mkOption {
      type = types.str;
      default = "${cfg.home}/.config";
      description = "XDG config root for the kiosk session.";
    };

    environment = mkOption {
      type = types.attrsOf types.str;
      default = { };
      description = "Extra environment variables for the Korri kiosk session.";
    };

    path = mkOption {
      type = types.listOf types.package;
      default = with pkgs; [
        coreutils
        dbus
      ];
      description = "Packages added to PATH for the kiosk session service.";
    };

    wants = mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = "Additional systemd units wanted by korri-kiosk.service.";
    };

    after = mkOption {
      type = types.listOf types.str;
      default = [ "network.target" ];
      description = "Systemd units that korri-kiosk.service starts after.";
    };

    client = {
      command = mkOption {
        type = types.str;
        default = lib.getExe config.services.korri.client.package;
        defaultText = lib.literalExpression "lib.getExe config.services.korri.client.package";
        description = ''
          Command launched from the product-owned kiosk session. Defaults to the
          selected `services.korri.client.package` executable.
        '';
      };
    };

    sway = {
      package = mkOption {
        type = types.package;
        default = pkgs.sway;
        description = "Sway package used for the first Korri kiosk compositor backend.";
      };

      extraPackages = mkOption {
        type = types.listOf types.package;
        default = [ ];
        description = "Additional packages available to Sway config fragments.";
      };

      extraConfig = mkOption {
        type = types.lines;
        default = "";
        description = ''
          Platform-provided Sway configuration fragments. Hardware facts such as
          display transforms, touchscreen calibration, and device-specific input
          maps belong here or in platform modules, not in Korri defaults.
        '';
      };

      configFile = mkOption {
        type = types.path;
        readOnly = true;
        default = swayConfig;
        description = "Generated Sway config consumed by korri-kiosk.service.";
      };
    };

    input = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable the product input bridge for the kiosk session.";
      };

      required = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Require a declared normalized-input provider before evaluating the
          kiosk. Full appliance images should set this to true; non-interactive
          fixtures can set `optOutReason` instead.
        '';
      };

      optOutReason = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Reason normalized appliance input is deliberately not provided.";
      };

      provider = {
        enable = mkOption {
          type = types.bool;
          default = false;
          description = "Declare that a platform adapter supplies normalized appliance input.";
        };

        services = mkOption {
          type = types.listOf types.str;
          default = [ ];
          description = "Platform input service units that must start before the Korri kiosk session.";
        };
      };
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.user != "";
        message = "services.korri.kiosk.user must not be empty.";
      }
      {
        assertion = lib.hasPrefix "/" cfg.runtimeDir;
        message = ''
          services.korri.kiosk.runtimeDir must be an absolute path (got
          "${cfg.runtimeDir}").
        '';
      }
      {
        assertion = lib.hasPrefix "/run/" cfg.runtimeDir;
        message = ''
          services.korri.kiosk.runtimeDir must live under /run so systemd can
          own the session runtime directory (got "${cfg.runtimeDir}").
        '';
      }
      {
        assertion = !(cfg.createUser && cfg.user == "root");
        message = ''
          services.korri.kiosk.createUser cannot manage the root user. Set
          createUser = false when a constrained platform adapter intentionally
          runs the kiosk as root.
        '';
      }
      {
        assertion = !inputRequiredWithoutProvider;
        message = ''
          services.korri.kiosk.input.required is true, but no normalized input
          provider was declared. Set services.korri.kiosk.input.provider.enable
          with provider services, or set input.optOutReason for deliberate
          non-interactive configurations.
        '';
      }
    ];

    warnings = lib.optional (cfg.input.optOutReason != null) ''
      services.korri.kiosk input provider was explicitly opted out:
      ${cfg.input.optOutReason}
    '';

    users.groups = mkIf cfg.createUser {
      ${groupName} = { };
    };

    users.users = mkIf cfg.createUser {
      ${cfg.user} = {
        isSystemUser = true;
        group = groupName;
        home = cfg.home;
        createHome = true;
      };
    };

    services.korri.client.enable = mkDefault true;
    services.korri.inputd = mkIf cfg.input.enable {
      enable = mkDefault true;
      before = [ "korri-kiosk.service" ];
    };

    systemd.services."korri-kiosk" = {
      description = "Korri appliance kiosk session";
      wantedBy = [ "multi-user.target" ];
      wants = cfg.wants ++ lib.optional cfg.input.enable "korri-inputd.service" ++ providerServices;
      after = cfg.after ++ lib.optional cfg.input.enable "korri-inputd.service" ++ providerServices;
      environment = sessionEnvironment;
      path = cfg.path ++ [ cfg.sway.package ] ++ cfg.sway.extraPackages;
      serviceConfig = {
        ExecStart = "${pkgs.dbus}/bin/dbus-run-session -- ${cfg.sway.package}/bin/sway --config ${swayConfig}";
        Restart = "always";
        RestartSec = 2;
        User = cfg.user;
        Group = groupName;
        WorkingDirectory = cfg.home;
        RuntimeDirectory = runtimeDirectoryName;
        RuntimeDirectoryMode = "0700";
      };
    };
  };
}
