{ korri }:

{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.korri.compositor;
  groupName =
    if cfg.group != null then
      cfg.group
    else if cfg.createUser then
      cfg.user
    else
      null;
  runtimeDirectoryName = lib.removePrefix "/run/" cfg.runtimeDir;
  sessionBusServices = lib.optionals (cfg.sessionBus.mode == "existing") cfg.sessionBus.services;
  ownsRuntimeDir = cfg.sessionBus.mode == "private";

  # Inputd ordering is wired in by the input module (U3), since that's where
  # the `services.korri.input.inputd.*` options live. Until then, the
  # compositor module only auto-enables the kiosk-surface peers it knows
  # about (client + cli). The KORRI_DESKTOP_INPUTD_URL env var below uses
  # the documented inputd default port 3002; once the input module lands,
  # this becomes a reference to `services.korri.input.inputd.port`.
  inputdDefaultPort = 3002;

  inherit (lib)
    mkDefault
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    types
    ;

  kioskClientCommand = cfg.kiosk.command;
  swayCommand = "${cfg.sway.package}/bin/sway --config ${swayConfig}";
  sessionCommand =
    if cfg.sessionBus.mode == "private" then
      "${pkgs.dbus}/bin/dbus-run-session -- ${swayCommand}"
    else
      swayCommand;
  kioskClientLauncher = pkgs.writeShellScript "korri-compositor-kiosk-client" ''
    while true; do
      set +e
      ${kioskClientCommand}
      status=$?
      set -e
      echo "korri-compositor-kiosk-client: client exited with status $status; restarting" >&2
      sleep 2
    done
  '';

  swayConfigPrelude = ''
    # Generated by services.korri.compositor. Platform modules may append
    # display/input fragments through services.korri.compositor.sway.extraConfig.
    default_border none
    default_floating_border none
    hide_edge_borders both
  '';

  swayKioskExec = ''
    exec --no-startup-id ${kioskClientLauncher}
  '';

  swayConfig = pkgs.writeText "korri-compositor-sway.conf" (
    swayConfigPrelude
    + (lib.optionalString cfg.kiosk.enable swayKioskExec)
    + "\n"
    + cfg.sway.extraConfig
  );

  sessionEnvironment =
    cfg.environment
    // {
      HOME = cfg.home;
      XDG_RUNTIME_DIR = cfg.runtimeDir;
      XDG_STATE_HOME = cfg.stateHome;
      XDG_DATA_HOME = cfg.dataHome;
      XDG_CONFIG_HOME = cfg.configHome;
    }
    // lib.optionalAttrs cfg.kiosk.enable {
      KORRI_KIOSK = "1";
      KORRI_DESKTOP_INPUTD_URL = "ws://127.0.0.1:${toString inputdDefaultPort}";
      KORRI_NATIVE_BRIDGE_URL = "ws://127.0.0.1:${toString inputdDefaultPort}";
    }
    // lib.optionalAttrs (cfg.sessionBus.mode == "existing" && cfg.sessionBus.address != null) {
      DBUS_SESSION_BUS_ADDRESS = cfg.sessionBus.address;
    };
in
{
  imports = [
    korri.nixosModules.korri-cli
  ];

  options.services.korri.compositor = {
    enable = mkEnableOption "Korri compositor session (Sway/Wayland substrate)";

    user = mkOption {
      type = types.str;
      default = "korri-compositor";
      description = ''
        Unix user that owns the Korri compositor session. Platform adapters
        for constrained guests may set this to `root` only when they also
        set `createUser = false`.
      '';
    };

    group = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "Unix group for the Korri compositor session. Defaults to `services.korri.compositor.user`.";
    };

    createUser = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Create the configured compositor user and group. Disable when a
        platform adapter supplies the user itself, including constrained
        guests that run the session as root.
      '';
    };

    home = mkOption {
      type = types.str;
      default = if cfg.user == "root" then "/root" else "/var/lib/korri-compositor";
      description = "Home directory used by the compositor session and any product client launched from it.";
    };

    runtimeDir = mkOption {
      type = types.str;
      default = "/run/korri-compositor";
      description = "Runtime directory exposed to the compositor as XDG_RUNTIME_DIR.";
    };

    stateHome = mkOption {
      type = types.str;
      default = "${cfg.home}/.local/state";
      description = "XDG state root for the compositor session.";
    };

    dataHome = mkOption {
      type = types.str;
      default = "${cfg.home}/.local/share";
      description = "XDG data root for the compositor session.";
    };

    configHome = mkOption {
      type = types.str;
      default = "${cfg.home}/.config";
      description = "XDG config root for the compositor session.";
    };

    environment = mkOption {
      type = types.attrsOf types.str;
      default = { };
      description = "Extra environment variables for the Korri compositor session.";
    };

    path = mkOption {
      type = types.listOf types.package;
      default = with pkgs; [
        coreutils
        dbus
        cfg.gamescope.package
      ];
      description = "Packages added to PATH for the compositor session service.";
    };

    gamescope = {
      package = mkOption {
        type = types.package;
        default = pkgs.gamescope;
        description = "Gamescope package available to foreground launches from the compositor session.";
      };
    };

    sessionBus = {
      mode = mkOption {
        type = types.enum [
          "private"
          "existing"
        ];
        default = "private";
        description = ''
          D-Bus session bus strategy for the compositor.

          `private` starts Sway with dbus-run-session and lets Korri own the
          runtime directory. `existing` starts Sway directly with a
          platform-owned DBUS_SESSION_BUS_ADDRESS; platform modules use this
          when a constrained guest or device substrate must own the bus.
        '';
      };

      address = mkOption {
        type = types.nullOr types.str;
        default = null;
        example = "unix:path=/run/user/0/bus";
        description = "Existing session bus address used when sessionBus.mode = \"existing\".";
      };

      services = mkOption {
        type = types.listOf types.str;
        default = [ ];
        example = [ "platform-session-dbus.service" ];
        description = ''
          Platform-owned service units that provide the existing session bus.
          These units are wanted, required, and ordered before korri-compositor
          when sessionBus.mode = "existing".
        '';
      };
    };

    wants = mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = "Additional systemd units wanted by korri-compositor.service.";
    };

    after = mkOption {
      type = types.listOf types.str;
      default = [ "network.target" ];
      description = "Systemd units that korri-compositor.service starts after.";
    };

    sway = {
      package = mkOption {
        type = types.package;
        default = pkgs.sway;
        description = "Sway package used for the Korri compositor backend.";
      };

      extraPackages = mkOption {
        type = types.listOf types.package;
        default = [ ];
        description = "Additional packages available to Sway config fragments.";
      };

      extraConfig = mkOption {
        type = types.lines;
        default = "";
        description = ''
          Platform-provided Sway configuration fragments. Hardware facts such as
          display transforms, touchscreen calibration, and device-specific input
          maps belong here or in platform modules, not in Korri defaults.
        '';
      };

      configFile = mkOption {
        type = types.path;
        readOnly = true;
        default = swayConfig;
        description = "Generated Sway config consumed by korri-compositor.service.";
      };
    };

    kiosk = {
      enable = mkEnableOption ''
        the local Korri kiosk surface (the product client launched from the
        compositor session). Disabled by default so that the compositor can
        host a headless streaming appliance (aka shape) without a local GUI.
      '';

      launcher = mkOption {
        type = types.path;
        readOnly = true;
        default = kioskClientLauncher;
        description = "Generated kiosk client launcher script used by the Sway config.";
      };

      command = mkOption {
        type = types.str;
        default = lib.getExe config.services.korri.client.package;
        defaultText = lib.literalExpression "lib.getExe config.services.korri.client.package";
        description = ''
          Shell command launched from the product-owned compositor session
          when `services.korri.compositor.kiosk.enable = true`. Defaults to
          the selected `services.korri.client.package` executable. Arguments
          are supported because the module writes this command into a session
          wrapper script rather than treating it as a single argv word.
        '';
      };
    };
  };

  config = mkMerge [
    {
      # Cross-tree assertion lives outside the `mkIf cfg.enable` gate so it
      # fires when a host sets `compositor.kiosk.enable = true` without
      # `compositor.enable = true`. Without this gate, the dormant kiosk
      # sub-tree would silently produce no systemd unit; this assertion
      # makes the contradiction loud.
      assertions = lib.optionals cfg.kiosk.enable [
        {
          assertion = cfg.enable;
          message = ''
            services.korri.compositor.kiosk.enable = true requires
            services.korri.compositor.enable = true. The kiosk surface is a
            sub-tree of the compositor substrate and cannot run without it.
          '';
        }
      ];
    }
    (mkIf cfg.enable {
      assertions = [
        {
          assertion = cfg.user != "";
          message = "services.korri.compositor.user must not be empty.";
        }
        {
          assertion = lib.hasPrefix "/" cfg.runtimeDir;
          message = ''
            services.korri.compositor.runtimeDir must be an absolute path (got
            "${cfg.runtimeDir}").
          '';
        }
        {
          assertion = lib.hasPrefix "/run/" cfg.runtimeDir;
          message = ''
            services.korri.compositor.runtimeDir must live under /run so systemd
            can own the session runtime directory (got "${cfg.runtimeDir}").
          '';
        }
        {
          assertion = !(cfg.createUser && cfg.user == "root");
          message = ''
            services.korri.compositor.createUser cannot manage the root user. Set
            createUser = false when a constrained platform adapter intentionally
            runs the compositor as root.
          '';
        }
        {
          assertion =
            cfg.sessionBus.mode != "existing"
            || (cfg.sessionBus.address != null && cfg.sessionBus.address != "");
          message = ''
            services.korri.compositor.sessionBus.address must be set when
            sessionBus.mode = "existing".
          '';
        }
      ];

      users.groups = mkIf (cfg.createUser && groupName != null) {
        ${groupName} = { };
      };

      users.users = mkIf cfg.createUser {
        ${cfg.user} = {
          isSystemUser = true;
          group = groupName;
          home = cfg.home;
          createHome = true;
        };
      };

      # Auto-enable the local Korri client + CLI only when the kiosk surface
      # is on. Headless compositor (aka) intentionally does not install or
      # launch the client.
      services.korri.client.enable = mkIf cfg.kiosk.enable (mkDefault true);
      services.korri.cli.enable = mkIf cfg.kiosk.enable (mkDefault true);

      systemd.services."korri-compositor" = {
        description = "Korri appliance compositor session";
        wantedBy = [ "multi-user.target" ];
        wants = cfg.wants ++ sessionBusServices;
        requires = sessionBusServices;
        after = cfg.after ++ sessionBusServices;
        environment = sessionEnvironment;
        path = cfg.path ++ [ cfg.sway.package ] ++ cfg.sway.extraPackages;
        unitConfig = {
          StartLimitBurst = 5;
          StartLimitIntervalSec = 60;
        };
        serviceConfig = {
          ExecStart = sessionCommand;
          Restart = "always";
          RestartSec = 2;
          User = cfg.user;
          WorkingDirectory = cfg.home;
        }
        // lib.optionalAttrs ownsRuntimeDir {
          RuntimeDirectory = runtimeDirectoryName;
          RuntimeDirectoryMode = "0700";
        }
        // lib.optionalAttrs (groupName != null) {
          Group = groupName;
        };
      };
    })
  ];
}
