{ korri }:

{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.korri.kiosk;
  groupName =
    if cfg.group != null then
      cfg.group
    else if cfg.createUser then
      cfg.user
    else
      null;
  runtimeDirectoryName = lib.removePrefix "/run/" cfg.runtimeDir;
  providerServices = cfg.input.provider.services;
  sessionBusServices = lib.optionals (cfg.sessionBus.mode == "existing") cfg.sessionBus.services;
  ownsRuntimeDir = cfg.sessionBus.mode == "private";
  requiredInputServices = lib.optional cfg.input.enable "korri-inputd.service" ++ providerServices;
  inputRequiredWithoutProvider =
    cfg.input.required
    && (!(cfg.input.provider.enable) || cfg.input.provider.name == null)
    && cfg.input.optOutReason == null;
  providerServicesWithoutProvider = providerServices != [ ] && !(cfg.input.provider.enable);

  inherit (lib)
    mkDefault
    mkEnableOption
    mkIf
    mkOption
    types
    ;

  clientCommand = cfg.client.command;
  swayCommand = "${cfg.sway.package}/bin/sway --config ${swayConfig}";
  sessionCommand =
    if cfg.sessionBus.mode == "private" then
      "${pkgs.dbus}/bin/dbus-run-session -- ${swayCommand}"
    else
      swayCommand;
  clientLauncher = pkgs.writeShellScript "korri-kiosk-client" ''
    set +e
    ${clientCommand}
    status=$?
    set -e
    ${cfg.sway.package}/bin/swaymsg exit >/dev/null 2>&1 || true
    exit "$status"
  '';
  swayConfig = pkgs.writeText "korri-kiosk-sway.conf" ''
    # Generated by services.korri.kiosk. Platform modules may append
    # display/input fragments through services.korri.kiosk.sway.extraConfig.
    exec --no-startup-id ${clientLauncher}

    ${cfg.sway.extraConfig}
  '';

  sessionEnvironment =
    cfg.environment
    // {
      HOME = cfg.home;
      XDG_RUNTIME_DIR = cfg.runtimeDir;
      XDG_STATE_HOME = cfg.stateHome;
      XDG_DATA_HOME = cfg.dataHome;
      XDG_CONFIG_HOME = cfg.configHome;
      KORRI_KIOSK = "1";
    }
    // lib.optionalAttrs cfg.input.enable {
      KORRI_NATIVE_BRIDGE_URL = "ws://127.0.0.1:${toString config.services.korri.inputd.port}";
    }
    // lib.optionalAttrs (cfg.sessionBus.mode == "existing" && cfg.sessionBus.address != null) {
      DBUS_SESSION_BUS_ADDRESS = cfg.sessionBus.address;
    };
in
{
  imports = [
    korri.nixosModules.korri-cli
  ];

  options.services.korri.kiosk = {
    enable = mkEnableOption "Korri appliance kiosk session";

    user = mkOption {
      type = types.str;
      default = "korri-kiosk";
      description = ''
        Unix user that owns the Korri kiosk compositor session. Platform
        adapters for constrained guests may set this to `root` only when they
        also set `createUser = false`.
      '';
    };

    group = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "Unix group for the Korri kiosk session. Defaults to `services.korri.kiosk.user`.";
    };

    createUser = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Create the configured kiosk user and group. Disable when a platform
        adapter supplies the user itself, including constrained guests that run
        the session as root.
      '';
    };

    home = mkOption {
      type = types.str;
      default = if cfg.user == "root" then "/root" else "/var/lib/korri-kiosk";
      description = "Home directory used by the kiosk session and Korri desktop wrapper.";
    };

    runtimeDir = mkOption {
      type = types.str;
      default = "/run/korri-kiosk";
      description = "Runtime directory exposed to the kiosk compositor as XDG_RUNTIME_DIR.";
    };

    stateHome = mkOption {
      type = types.str;
      default = "${cfg.home}/.local/state";
      description = "XDG state root for the kiosk session.";
    };

    dataHome = mkOption {
      type = types.str;
      default = "${cfg.home}/.local/share";
      description = "XDG data root for the kiosk session.";
    };

    configHome = mkOption {
      type = types.str;
      default = "${cfg.home}/.config";
      description = "XDG config root for the kiosk session.";
    };

    environment = mkOption {
      type = types.attrsOf types.str;
      default = { };
      description = "Extra environment variables for the Korri kiosk session.";
    };

    path = mkOption {
      type = types.listOf types.package;
      default = with pkgs; [
        coreutils
        dbus
      ];
      description = "Packages added to PATH for the kiosk session service.";
    };

    sessionBus = {
      mode = mkOption {
        type = types.enum [
          "private"
          "existing"
        ];
        default = "private";
        description = ''
          D-Bus session bus strategy for the kiosk compositor.

          `private` starts Sway with dbus-run-session and lets Korri own the
          runtime directory. `existing` starts Sway directly with a
          platform-owned DBUS_SESSION_BUS_ADDRESS; platform modules use this
          when a constrained guest or device substrate must own the bus.
        '';
      };

      address = mkOption {
        type = types.nullOr types.str;
        default = null;
        example = "unix:path=/run/user/0/bus";
        description = "Existing session bus address used when sessionBus.mode = \"existing\".";
      };

      services = mkOption {
        type = types.listOf types.str;
        default = [ ];
        example = [ "platform-session-dbus.service" ];
        description = ''
          Platform-owned service units that provide the existing session bus.
          These units are wanted, required, and ordered before korri-kiosk when
          sessionBus.mode = "existing".
        '';
      };
    };

    wants = mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = "Additional systemd units wanted by korri-kiosk.service.";
    };

    after = mkOption {
      type = types.listOf types.str;
      default = [ "network.target" ];
      description = "Systemd units that korri-kiosk.service starts after.";
    };

    client = {
      launcher = mkOption {
        type = types.path;
        readOnly = true;
        default = clientLauncher;
        description = "Generated client launcher script used by the Sway kiosk config.";
      };

      command = mkOption {
        type = types.str;
        default = lib.getExe config.services.korri.client.package;
        defaultText = lib.literalExpression "lib.getExe config.services.korri.client.package";
        description = ''
          Shell command launched from the product-owned kiosk session. Defaults
          to the selected `services.korri.client.package` executable. Arguments
          are supported because the module writes this command into a session
          wrapper script rather than treating it as a single argv word.
        '';
      };
    };

    sway = {
      package = mkOption {
        type = types.package;
        default = pkgs.sway;
        description = "Sway package used for the first Korri kiosk compositor backend.";
      };

      extraPackages = mkOption {
        type = types.listOf types.package;
        default = [ ];
        description = "Additional packages available to Sway config fragments.";
      };

      extraConfig = mkOption {
        type = types.lines;
        default = "";
        description = ''
          Platform-provided Sway configuration fragments. Hardware facts such as
          display transforms, touchscreen calibration, and device-specific input
          maps belong here or in platform modules, not in Korri defaults.
        '';
      };

      configFile = mkOption {
        type = types.path;
        readOnly = true;
        default = swayConfig;
        description = "Generated Sway config consumed by korri-kiosk.service.";
      };
    };

    input = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable the product input bridge for the kiosk session.";
      };

      required = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Require a declared normalized-input provider before evaluating the
          kiosk. Full appliance images should set this to true; non-interactive
          fixtures can set `optOutReason` instead.
        '';
      };

      optOutReason = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Reason normalized appliance input is deliberately not provided.";
      };

      provider = {
        enable = mkOption {
          type = types.bool;
          default = false;
          description = "Declare that a platform adapter supplies normalized appliance input.";
        };

        name = mkOption {
          type = types.nullOr types.str;
          default = null;
          example = "x86-seat-input";
          description = "Human-readable provider name for evaluation diagnostics and downstream review.";
        };

        services = mkOption {
          type = types.listOf types.str;
          default = [ ];
          description = "Platform input service units that must start before the Korri kiosk session.";
        };
      };
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.user != "";
        message = "services.korri.kiosk.user must not be empty.";
      }
      {
        assertion = lib.hasPrefix "/" cfg.runtimeDir;
        message = ''
          services.korri.kiosk.runtimeDir must be an absolute path (got
          "${cfg.runtimeDir}").
        '';
      }
      {
        assertion = lib.hasPrefix "/run/" cfg.runtimeDir;
        message = ''
          services.korri.kiosk.runtimeDir must live under /run so systemd can
          own the session runtime directory (got "${cfg.runtimeDir}").
        '';
      }
      {
        assertion = !(cfg.createUser && cfg.user == "root");
        message = ''
          services.korri.kiosk.createUser cannot manage the root user. Set
          createUser = false when a constrained platform adapter intentionally
          runs the kiosk as root.
        '';
      }
      {
        assertion =
          cfg.sessionBus.mode != "existing"
          || (cfg.sessionBus.address != null && cfg.sessionBus.address != "");
        message = ''
          services.korri.kiosk.sessionBus.address must be set when
          sessionBus.mode = "existing".
        '';
      }
      {
        assertion = !inputRequiredWithoutProvider;
        message = ''
          services.korri.kiosk.input.required is true, but no named normalized
          input provider was declared. Set services.korri.kiosk.input.provider
          with enable = true and name, or set input.optOutReason for deliberate
          non-interactive configurations.
        '';
      }
      {
        assertion = !providerServicesWithoutProvider;
        message = ''
          services.korri.kiosk.input.provider.services was set while
          input.provider.enable is false. Enable the named provider or remove
          the provider service ordering.
        '';
      }
    ];

    warnings = lib.optional (cfg.input.optOutReason != null) ''
      services.korri.kiosk input provider was explicitly opted out:
      ${cfg.input.optOutReason}
    '';

    users.groups = mkIf (cfg.createUser && groupName != null) {
      ${groupName} = { };
    };

    users.users = mkIf cfg.createUser {
      ${cfg.user} = {
        isSystemUser = true;
        group = groupName;
        home = cfg.home;
        createHome = true;
      };
    };

    services.korri.client.enable = mkDefault true;
    services.korri.cli.enable = mkDefault true;
    services.korri.inputd = mkIf cfg.input.enable {
      enable = mkDefault true;
      before = [ "korri-kiosk.service" ];
    };

    systemd.services."korri-kiosk" = {
      description = "Korri appliance kiosk session";
      wantedBy = [ "multi-user.target" ];
      wants = cfg.wants ++ requiredInputServices ++ sessionBusServices;
      requires = lib.optionals cfg.input.required requiredInputServices ++ sessionBusServices;
      after = cfg.after ++ requiredInputServices ++ sessionBusServices;
      environment = sessionEnvironment;
      path = cfg.path ++ [ cfg.sway.package ] ++ cfg.sway.extraPackages;
      unitConfig = {
        StartLimitBurst = 5;
        StartLimitIntervalSec = 60;
      };
      serviceConfig = {
        ExecStart = sessionCommand;
        Restart = "always";
        RestartSec = 2;
        User = cfg.user;
        WorkingDirectory = cfg.home;
      }
      // lib.optionalAttrs ownsRuntimeDir {
        RuntimeDirectory = runtimeDirectoryName;
        RuntimeDirectoryMode = "0700";
      }
      // lib.optionalAttrs (groupName != null) {
        Group = groupName;
      };
    };
  };
}
