import assert from "node:assert/strict"

/** Drive Caliper's own page placements and source picker, not a substitute DOM. */
export async function verifyLivePages(page, frame) {
  const pages = frame.locator(".pt-gallery-group").filter({ has: frame.locator(".pt-gallery-head .layer-page") })
  const place = async name => {
    const card = pages.getByRole("button", { name: `Open ${name}`, exact: true })
    await card.dispatchEvent("click")
    const object = frame.locator(".pt-object").filter({ has: frame.locator(".lab-part-mount .pico-caliper-mount") })
    await object.waitFor({ state: "attached" })
    await object.dispatchEvent("pointerdown")
    const source = frame.getByRole("combobox", { name: `Data source for ${name}`, exact: true })
    return { object, source, close: () => card.dispatchEvent("click") }
  }
  const settings = await place("Settings")
  await settings.object.getByRole("tab", { name: "PLUGINS", exact: true }).dispatchEvent("click")
  await settings.object.getByRole("button", { name: /mGBA/ }).dispatchEvent("click")
  assert.equal(await settings.object.locator('[data-lit="true"]').innerText(), "OFF")
  await settings.object.locator(".pico-screen").evaluate(e => { e.dataset.reseedIdentity = "retained" })
  await settings.source.selectOption("settings-saving")
  await settings.object.getByText("SAVING", { exact: true }).waitFor()
  assert.equal(await settings.object.locator(".pico-screen").getAttribute("data-reseed-identity"), "retained")
  await settings.source.selectOption("settings-problem")
  await settings.object.getByText("PREVIEW: Setting was not saved", { exact: true }).waitFor()
  await settings.source.selectOption("problem")
  await settings.object.getByText("PREVIEW: Launch failed", { exact: true }).waitFor()
  await settings.object.locator(".pico-caliper-mount").press("Escape")
  await settings.object.locator(".pico-panel-screen").waitFor()
  await settings.close()

  const find = await place("Find")
  await frame.getByRole("combobox", { name: "Preview frame device size", exact: true }).selectOption("rg353m")
  assert.equal(await find.object.locator(".pico-result-row-title").evaluateAll(titles =>
    titles.every(title => title.scrollWidth <= title.clientWidth + 1)), true,
    "RG353M must show readable game titles, not only provenance and ellipses")
  await find.object.getByRole("button", { name: "Type T", exact: true }).dispatchEvent("click")
  assert.equal(await find.object.locator(".pico-query-field-text").innerText(), "T")
  await find.object.getByRole("button", { name: /Tetris, GB/ }).dispatchEvent("click")
  await find.object.locator(".pico-game-detail").waitFor()
  await find.object.locator(".pico-caliper-mount").press("Escape")
  await find.object.locator(".pico-library-browser").waitFor()
  assert.equal(await find.object.locator(".pico-query-field-text").innerText(), "T")
  await find.object.getByRole("button", { name: /Tetris, GB/ }).dispatchEvent("click")
  await find.object.getByRole("button", { name: /PLAY/ }).dispatchEvent("click")
  assert.equal(await find.object.getByRole("button", { name: "This device", exact: true }).count(), 1)
  await find.object.getByRole("button", { name: "zao", exact: true }).dispatchEvent("click")
  await find.object.getByText("PREVIEW: Starting game", { exact: true }).waitFor()
  await find.close()

  const detail = await place("Game Detail")
  const remove = detail.object.getByRole("button", { name: "Remove from device", exact: true })
  await remove.focus()
  await remove.press("Enter")
  const dialog = detail.object.getByRole("dialog")
  await dialog.waitFor()
  const cancel = dialog.getByRole("button", { name: "CANCEL", exact: true })
  const confirm = dialog.getByRole("button").first()
  assert.equal(await cancel.evaluate(e => document.activeElement === e), true, "confirmation focuses the safe action")
  await cancel.press("Tab")
  assert.equal(await confirm.evaluate(e => document.activeElement === e), true, "Tab stays in the confirmation")
  await confirm.press("Shift+Tab")
  assert.equal(await cancel.evaluate(e => document.activeElement === e), true)
  await cancel.press("Escape")
  assert.equal(await remove.evaluate(e => document.activeElement === e), true, "Escape restores the opener")
  assert.equal(await detail.object.getByRole("dialog").count(), 0)
  assert.equal(await detail.object.locator(".pico-launch-stage").count(), 0)
  await detail.close()

  const overlay = await place("Gameplay Overlay")
  await overlay.object.getByRole("button", { name: /Fast forward/ }).dispatchEvent("click")
  assert.match(await overlay.object.getByRole("button", { name: /Fast forward/ }).innerText(), /ON/)
  await overlay.source.selectOption("overlay-problem")
  await overlay.object.getByText("PREVIEW: Overlay command failed", { exact: true }).waitFor()
  await overlay.object.getByRole("button", { name: "TRY AGAIN", exact: true }).dispatchEvent("click")
  assert.equal(await overlay.object.locator(".pico-pause-menu-problem").count(), 0)
  await overlay.close()

  const home = await place("Home")
  await home.source.selectOption("catalog-error")
  await home.object.getByText("PREVIEW: Library could not be read", { exact: true }).waitFor()
  await home.source.selectOption("running")
  await home.object.getByText("PREVIEW: Game running", { exact: true }).waitFor()
  await home.source.selectOption("problem")
  await home.object.getByText("PREVIEW: Launch failed", { exact: true }).waitFor()
  await home.source.selectOption("ready")
  await home.object.locator(".pico-cart-shelf").waitFor()
  await home.close()
  console.log("PASS: five live page placements, source reseeding, Find return path, explicit launch location, confirmation and overlay feedback")
}
