// Declaration-only Moonlight streaming plugin.
//
// Artemis owns certificates, host discovery, pairing, the Moonlight protocol,
// Activity startup, and live Game effects at the Android edge. This declaration
// owns the stable transport identity, Android implementation selection,
// Sunshine app identity, and the controls that implementation may fulfill.
const transport = "@korri:moonlight/moonlight"

const declaration = {
  namespace: "@korri",
  name: "moonlight",
  title: "Moonlight",
  description: "Owns Moonlight streaming through the Android Artemis edge.",
  contributes: {
    config: {
      transports: {
        moonlight: {
          id: transport,
          android: {
            implementation: "artemis",
            sunshineApp: "Korri Stream",
          },
        },
      },
    },
    sessionControls: {
      fill: {
        order: 0,
        id: "@korri:moonlight/fill",
        owner: { kind: "transport", id: transport },
        label: "Screen fit",
        description: "Switch between fit and crop to fill",
        interaction: {
          kind: "toggle",
          trueLabel: "crop to fill",
          falseLabel: "fit (letterbox)",
        },
        effect: "@korri:moonlight/set-fill-mode",
      },
      keyboard: {
        order: 1,
        id: "@korri:moonlight/keyboard",
        owner: { kind: "transport", id: transport },
        label: "Toggle keyboard",
        interaction: { kind: "command" },
        effect: "@korri:moonlight/toggle-keyboard",
        dismissOnSuccess: true,
      },
      fullKeyboard: {
        order: 2,
        id: "@korri:moonlight/full-keyboard",
        owner: { kind: "transport", id: transport },
        label: "Full keyboard",
        interaction: { kind: "command" },
        effect: "@korri:moonlight/toggle-full-keyboard",
        dismissOnSuccess: true,
      },
      panZoom: {
        order: 3,
        id: "@korri:moonlight/pan-zoom",
        owner: { kind: "transport", id: transport },
        label: "Pan & zoom",
        interaction: { kind: "toggle" },
        effect: "@korri:moonlight/set-zoom-mode",
        dismissOnSuccess: true,
      },
      mouseMode: {
        order: 4,
        id: "@korri:moonlight/mouse-mode",
        owner: { kind: "transport", id: transport },
        label: "Mouse mode",
        interaction: {
          kind: "choice",
          options: [
            { value: "0", label: "Multi touch" },
            { value: "1", label: "Absolute touch" },
            { value: "2", label: "Track pad(Natural/Double tap to drag)" },
            { value: "3", label: "Track pad(Gaming/Long press to drag)" },
            { value: "4", label: "Disabled" },
            {
              value: "5",
              label: "Absolute touch (left/right click swapped)",
            },
          ],
        },
        effect: "@korri:moonlight/set-mouse-mode",
        dismissOnSuccess: true,
      },
      localCursor: {
        order: 5,
        id: "@korri:moonlight/local-cursor",
        owner: { kind: "transport", id: transport },
        label: "Toggle local mouse cursor(physical mouse needed)",
        interaction: { kind: "command" },
        effect: "@korri:moonlight/set-local-cursor",
        dismissOnSuccess: true,
      },
      rotateScreen: {
        order: 6,
        id: "@korri:moonlight/rotate-screen",
        owner: { kind: "transport", id: transport },
        label: "Rotate screen",
        interaction: { kind: "command" },
        effect: "@korri:moonlight/rotate-screen",
        dismissOnSuccess: true,
      },
      hud: {
        order: 7,
        id: "@korri:moonlight/hud",
        owner: { kind: "transport", id: transport },
        label: "Toggle HUD",
        interaction: { kind: "command" },
        effect: "@korri:moonlight/toggle-hud",
        dismissOnSuccess: true,
      },
      floatingMenu: {
        order: 8,
        id: "@korri:moonlight/floating-menu",
        owner: { kind: "transport", id: transport },
        label: "Floating menu button",
        interaction: { kind: "command" },
        effect: "@korri:moonlight/toggle-floating-menu",
        dismissOnSuccess: true,
      },
      keyboardController: {
        order: 9,
        id: "@korri:moonlight/keyboard-controller",
        owner: { kind: "transport", id: transport },
        label: "Keyboard as controller",
        interaction: { kind: "command" },
        effect: "@korri:moonlight/toggle-keyboard-controller",
        dismissOnSuccess: true,
      },
      touchSensitivity: {
        order: 10,
        id: "@korri:moonlight/touch-sensitivity",
        owner: { kind: "transport", id: transport },
        label: "Touch sensitivity",
        interaction: { kind: "command" },
        effect: "@korri:moonlight/switch-touch-sensitivity",
        dismissOnSuccess: true,
      },
      sgsrSharpness: {
        order: 11,
        id: "@korri:moonlight/sgsr-sharpness",
        owner: { kind: "transport", id: transport },
        label: "SGSR sharpness",
        interaction: { kind: "range", min: 0, max: 50, step: 1 },
        effect: "@korri:moonlight/set-sgsr-sharpness",
      },
      sgsrEdgeThreshold: {
        order: 12,
        id: "@korri:moonlight/sgsr-edge-threshold",
        owner: { kind: "transport", id: transport },
        label: "SGSR edge threshold",
        interaction: { kind: "range", min: 1, max: 32, step: 1 },
        effect: "@korri:moonlight/set-sgsr-edge-threshold",
      },
      faceButtonFlip: {
        order: 13,
        id: "@korri:moonlight/face-button-flip",
        owner: { kind: "transport", id: transport },
        label: "Flip A/B and X/Y",
        interaction: { kind: "toggle" },
        effect: "@korri:moonlight/set-face-button-flip",
      },
      rumble: {
        order: 14,
        id: "@korri:moonlight/rumble",
        owner: { kind: "transport", id: transport },
        label: "Rumble",
        interaction: { kind: "toggle" },
        effect: "@korri:moonlight/set-rumble",
      },
      pictureInPicture: {
        order: 15,
        id: "@korri:moonlight/picture-in-picture",
        owner: { kind: "transport", id: transport },
        label: "Picture-in-picture",
        interaction: { kind: "toggle" },
        effect: "@korri:moonlight/set-picture-in-picture",
      },
      disconnect: {
        order: 16,
        id: "@korri:moonlight/disconnect",
        owner: { kind: "transport", id: transport },
        label: "Disconnect",
        description: "Leave the host game running",
        interaction: { kind: "command" },
        effect: "@korri:moonlight/disconnect",
        dismissOnSuccess: true,
      },
      quitHost: {
        order: 17,
        id: "@korri:moonlight/quit-host",
        owner: { kind: "transport", id: transport },
        label: "Quit game on host",
        interaction: { kind: "command" },
        effect: "@korri:moonlight/quit-host",
        destructive: true,
        dismissOnSuccess: true,
      },
    },
  },
} as const

declaration
